package sdl

const (
	GAMEPAD_AXIS_LEFTX = iota
	GAMEPAD_AXIS_LEFTY
	GAMEPAD_AXIS_RIGHTX
	GAMEPAD_AXIS_RIGHTY
	GAMEPAD_AXIS_LEFT_TRIGGER
	GAMEPAD_AXIS_RIGHT_TRIGGER
	GAMEPAD_AXIS_COUNT

	GAMEPAD_AXIS_INVALID = -1
)
