// Code generated by "so bind"; DO NOT EDIT.

package sdl

import "solod.dev/so/c"
var _ c.Char

//so:extern SDLK_0
const Key0 = 48

//so:extern SDLK_1
const Key1 = 49

//so:extern SDLK_2
const Key2 = 50

//so:extern SDLK_3
const Key3 = 51

//so:extern SDLK_4
const Key4 = 52

//so:extern SDLK_5
const Key5 = 53

//so:extern SDLK_6
const Key6 = 54

//so:extern SDLK_7
const Key7 = 55

//so:extern SDLK_8
const Key8 = 56

//so:extern SDLK_9
const Key9 = 57

//so:extern SDLK_A
const KeyA = 97

//so:extern SDLK_AC_BACK
const KeyAC_BACK = 1073742106

//so:extern SDLK_AC_BOOKMARKS
const KeyAC_BOOKMARKS = 1073742110

//so:extern SDLK_AC_CLOSE
const KeyAC_CLOSE = 1073742099

//so:extern SDLK_AC_EXIT
const KeyAC_EXIT = 1073742100

//so:extern SDLK_AC_FORWARD
const KeyAC_FORWARD = 1073742107

//so:extern SDLK_AC_HOME
const KeyAC_HOME = 1073742105

//so:extern SDLK_AC_NEW
const KeyAC_NEW = 1073742097

//so:extern SDLK_AC_OPEN
const KeyAC_OPEN = 1073742098

//so:extern SDLK_AC_PRINT
const KeyAC_PRINT = 1073742102

//so:extern SDLK_AC_PROPERTIES
const KeyAC_PROPERTIES = 1073742103

//so:extern SDLK_AC_REFRESH
const KeyAC_REFRESH = 1073742109

//so:extern SDLK_AC_SAVE
const KeyAC_SAVE = 1073742101

//so:extern SDLK_AC_SEARCH
const KeyAC_SEARCH = 1073742104

//so:extern SDLK_AC_STOP
const KeyAC_STOP = 1073742108

//so:extern SDLK_AGAIN
const KeyAGAIN = 1073741945

//so:extern SDLK_ALTERASE
const KeyALTERASE = 1073741977

//so:extern SDLK_AMPERSAND
const KeyAMPERSAND = 38

//so:extern SDLK_APOSTROPHE
const KeyAPOSTROPHE = 39

//so:extern SDLK_APPLICATION
const KeyAPPLICATION = 1073741925

//so:extern SDLK_ASTERISK
const KeyASTERISK = 42

//so:extern SDLK_AT
const KeyAT = 64

//so:extern SDLK_B
const KeyB = 98

//so:extern SDLK_BACKSLASH
const KeyBACKSLASH = 92

//so:extern SDLK_BACKSPACE
const KeyBACKSPACE = 8

//so:extern SDLK_C
const KeyC = 99

//so:extern SDLK_CALL
const KeyCALL = 1073742113

//so:extern SDLK_CANCEL
const KeyCANCEL = 1073741979

//so:extern SDLK_CAPSLOCK
const KeyCAPSLOCK = 1073741881

//so:extern SDLK_CARET
const KeyCARET = 94

//so:extern SDLK_CHANNEL_DECREMENT
const KeyCHANNEL_DECREMENT = 1073742085

//so:extern SDLK_CHANNEL_INCREMENT
const KeyCHANNEL_INCREMENT = 1073742084

//so:extern SDLK_CLEAR
const KeyCLEAR = 1073741980

//so:extern SDLK_CLEARAGAIN
const KeyCLEARAGAIN = 1073741986

//so:extern SDLK_COLON
const KeyCOLON = 58

//so:extern SDLK_COMMA
const KeyCOMMA = 44

//so:extern SDLK_COPY
const KeyCOPY = 1073741948

//so:extern SDLK_CRSEL
const KeyCRSEL = 1073741987

//so:extern SDLK_CURRENCYSUBUNIT
const KeyCURRENCYSUBUNIT = 1073742005

//so:extern SDLK_CURRENCYUNIT
const KeyCURRENCYUNIT = 1073742004

//so:extern SDLK_CUT
const KeyCUT = 1073741947

//so:extern SDLK_D
const KeyD = 100

//so:extern SDLK_DBLAPOSTROPHE
const KeyDBLAPOSTROPHE = 34

//so:extern SDLK_DECIMALSEPARATOR
const KeyDECIMALSEPARATOR = 1073742003

//so:extern SDLK_DELETE
const KeyDELETE = 127

//so:extern SDLK_DOLLAR
const KeyDOLLAR = 36

//so:extern SDLK_DOWN
const KeyDOWN = 1073741905

//so:extern SDLK_E
const KeyE = 101

//so:extern SDLK_END
const KeyEND = 1073741901

//so:extern SDLK_ENDCALL
const KeyENDCALL = 1073742114

//so:extern SDLK_EQUALS
const KeyEQUALS = 61

//so:extern SDLK_ESCAPE
const KeyESCAPE = 27

//so:extern SDLK_EXCLAIM
const KeyEXCLAIM = 33

//so:extern SDLK_EXECUTE
const KeyEXECUTE = 1073741940

//so:extern SDLK_EXSEL
const KeyEXSEL = 1073741988

//so:extern SDLK_EXTENDED_MASK
const KeyEXTENDED_MASK = 536870912

//so:extern SDLK_F
const KeyF = 102

//so:extern SDLK_F1
const KeyF1 = 1073741882

//so:extern SDLK_F10
const KeyF10 = 1073741891

//so:extern SDLK_F11
const KeyF11 = 1073741892

//so:extern SDLK_F12
const KeyF12 = 1073741893

//so:extern SDLK_F13
const KeyF13 = 1073741928

//so:extern SDLK_F14
const KeyF14 = 1073741929

//so:extern SDLK_F15
const KeyF15 = 1073741930

//so:extern SDLK_F16
const KeyF16 = 1073741931

//so:extern SDLK_F17
const KeyF17 = 1073741932

//so:extern SDLK_F18
const KeyF18 = 1073741933

//so:extern SDLK_F19
const KeyF19 = 1073741934

//so:extern SDLK_F2
const KeyF2 = 1073741883

//so:extern SDLK_F20
const KeyF20 = 1073741935

//so:extern SDLK_F21
const KeyF21 = 1073741936

//so:extern SDLK_F22
const KeyF22 = 1073741937

//so:extern SDLK_F23
const KeyF23 = 1073741938

//so:extern SDLK_F24
const KeyF24 = 1073741939

//so:extern SDLK_F3
const KeyF3 = 1073741884

//so:extern SDLK_F4
const KeyF4 = 1073741885

//so:extern SDLK_F5
const KeyF5 = 1073741886

//so:extern SDLK_F6
const KeyF6 = 1073741887

//so:extern SDLK_F7
const KeyF7 = 1073741888

//so:extern SDLK_F8
const KeyF8 = 1073741889

//so:extern SDLK_F9
const KeyF9 = 1073741890

//so:extern SDLK_FIND
const KeyFIND = 1073741950

//so:extern SDLK_G
const KeyG = 103

//so:extern SDLK_GRAVE
const KeyGRAVE = 96

//so:extern SDLK_GREATER
const KeyGREATER = 62

//so:extern SDLK_H
const KeyH = 104

//so:extern SDLK_HASH
const KeyHASH = 35

//so:extern SDLK_HELP
const KeyHELP = 1073741941

//so:extern SDLK_HOME
const KeyHOME = 1073741898

//so:extern SDLK_I
const KeyI = 105

//so:extern SDLK_INSERT
const KeyINSERT = 1073741897

//so:extern SDLK_J
const KeyJ = 106

//so:extern SDLK_K
const KeyK = 107

//so:extern SDLK_KP_0
const KeyKP_0 = 1073741922

//so:extern SDLK_KP_00
const KeyKP_00 = 1073742000

//so:extern SDLK_KP_000
const KeyKP_000 = 1073742001

//so:extern SDLK_KP_1
const KeyKP_1 = 1073741913

//so:extern SDLK_KP_2
const KeyKP_2 = 1073741914

//so:extern SDLK_KP_3
const KeyKP_3 = 1073741915

//so:extern SDLK_KP_4
const KeyKP_4 = 1073741916

//so:extern SDLK_KP_5
const KeyKP_5 = 1073741917

//so:extern SDLK_KP_6
const KeyKP_6 = 1073741918

//so:extern SDLK_KP_7
const KeyKP_7 = 1073741919

//so:extern SDLK_KP_8
const KeyKP_8 = 1073741920

//so:extern SDLK_KP_9
const KeyKP_9 = 1073741921

//so:extern SDLK_KP_A
const KeyKP_A = 1073742012

//so:extern SDLK_KP_AMPERSAND
const KeyKP_AMPERSAND = 1073742023

//so:extern SDLK_KP_AT
const KeyKP_AT = 1073742030

//so:extern SDLK_KP_B
const KeyKP_B = 1073742013

//so:extern SDLK_KP_BACKSPACE
const KeyKP_BACKSPACE = 1073742011

//so:extern SDLK_KP_BINARY
const KeyKP_BINARY = 1073742042

//so:extern SDLK_KP_C
const KeyKP_C = 1073742014

//so:extern SDLK_KP_CLEAR
const KeyKP_CLEAR = 1073742040

//so:extern SDLK_KP_CLEARENTRY
const KeyKP_CLEARENTRY = 1073742041

//so:extern SDLK_KP_COLON
const KeyKP_COLON = 1073742027

//so:extern SDLK_KP_COMMA
const KeyKP_COMMA = 1073741957

//so:extern SDLK_KP_D
const KeyKP_D = 1073742015

//so:extern SDLK_KP_DBLAMPERSAND
const KeyKP_DBLAMPERSAND = 1073742024

//so:extern SDLK_KP_DBLVERTICALBAR
const KeyKP_DBLVERTICALBAR = 1073742026

//so:extern SDLK_KP_DECIMAL
const KeyKP_DECIMAL = 1073742044

//so:extern SDLK_KP_DIVIDE
const KeyKP_DIVIDE = 1073741908

//so:extern SDLK_KP_E
const KeyKP_E = 1073742016

//so:extern SDLK_KP_ENTER
const KeyKP_ENTER = 1073741912

//so:extern SDLK_KP_EQUALS
const KeyKP_EQUALS = 1073741927

//so:extern SDLK_KP_EQUALSAS400
const KeyKP_EQUALSAS400 = 1073741958

//so:extern SDLK_KP_EXCLAM
const KeyKP_EXCLAM = 1073742031

//so:extern SDLK_KP_F
const KeyKP_F = 1073742017

//so:extern SDLK_KP_GREATER
const KeyKP_GREATER = 1073742022

//so:extern SDLK_KP_HASH
const KeyKP_HASH = 1073742028

//so:extern SDLK_KP_HEXADECIMAL
const KeyKP_HEXADECIMAL = 1073742045

//so:extern SDLK_KP_LEFTBRACE
const KeyKP_LEFTBRACE = 1073742008

//so:extern SDLK_KP_LEFTPAREN
const KeyKP_LEFTPAREN = 1073742006

//so:extern SDLK_KP_LESS
const KeyKP_LESS = 1073742021

//so:extern SDLK_KP_MEMADD
const KeyKP_MEMADD = 1073742035

//so:extern SDLK_KP_MEMCLEAR
const KeyKP_MEMCLEAR = 1073742034

//so:extern SDLK_KP_MEMDIVIDE
const KeyKP_MEMDIVIDE = 1073742038

//so:extern SDLK_KP_MEMMULTIPLY
const KeyKP_MEMMULTIPLY = 1073742037

//so:extern SDLK_KP_MEMRECALL
const KeyKP_MEMRECALL = 1073742033

//so:extern SDLK_KP_MEMSTORE
const KeyKP_MEMSTORE = 1073742032

//so:extern SDLK_KP_MEMSUBTRACT
const KeyKP_MEMSUBTRACT = 1073742036

//so:extern SDLK_KP_MINUS
const KeyKP_MINUS = 1073741910

//so:extern SDLK_KP_MULTIPLY
const KeyKP_MULTIPLY = 1073741909

//so:extern SDLK_KP_OCTAL
const KeyKP_OCTAL = 1073742043

//so:extern SDLK_KP_PERCENT
const KeyKP_PERCENT = 1073742020

//so:extern SDLK_KP_PERIOD
const KeyKP_PERIOD = 1073741923

//so:extern SDLK_KP_PLUS
const KeyKP_PLUS = 1073741911

//so:extern SDLK_KP_PLUSMINUS
const KeyKP_PLUSMINUS = 1073742039

//so:extern SDLK_KP_POWER
const KeyKP_POWER = 1073742019

//so:extern SDLK_KP_RIGHTBRACE
const KeyKP_RIGHTBRACE = 1073742009

//so:extern SDLK_KP_RIGHTPAREN
const KeyKP_RIGHTPAREN = 1073742007

//so:extern SDLK_KP_SPACE
const KeyKP_SPACE = 1073742029

//so:extern SDLK_KP_TAB
const KeyKP_TAB = 1073742010

//so:extern SDLK_KP_VERTICALBAR
const KeyKP_VERTICALBAR = 1073742025

//so:extern SDLK_KP_XOR
const KeyKP_XOR = 1073742018

//so:extern SDLK_L
const KeyL = 108

//so:extern SDLK_LALT
const KeyLALT = 1073742050

//so:extern SDLK_LCTRL
const KeyLCTRL = 1073742048

//so:extern SDLK_LEFT
const KeyLEFT = 1073741904

//so:extern SDLK_LEFTBRACE
const KeyLEFTBRACE = 123

//so:extern SDLK_LEFTBRACKET
const KeyLEFTBRACKET = 91

//so:extern SDLK_LEFTPAREN
const KeyLEFTPAREN = 40

//so:extern SDLK_LEFT_TAB
const KeyLEFT_TAB = 536870913

//so:extern SDLK_LESS
const KeyLESS = 60

//so:extern SDLK_LEVEL5_SHIFT
const KeyLEVEL5_SHIFT = 536870914

//so:extern SDLK_LGUI
const KeyLGUI = 1073742051

//so:extern SDLK_LHYPER
const KeyLHYPER = 536870918

//so:extern SDLK_LMETA
const KeyLMETA = 536870916

//so:extern SDLK_LSHIFT
const KeyLSHIFT = 1073742049

//so:extern SDLK_M
const KeyM = 109

//so:extern SDLK_MEDIA_EJECT
const KeyMEDIA_EJECT = 1073742094

//so:extern SDLK_MEDIA_FAST_FORWARD
const KeyMEDIA_FAST_FORWARD = 1073742089

//so:extern SDLK_MEDIA_NEXT_TRACK
const KeyMEDIA_NEXT_TRACK = 1073742091

//so:extern SDLK_MEDIA_PAUSE
const KeyMEDIA_PAUSE = 1073742087

//so:extern SDLK_MEDIA_PLAY
const KeyMEDIA_PLAY = 1073742086

//so:extern SDLK_MEDIA_PLAY_PAUSE
const KeyMEDIA_PLAY_PAUSE = 1073742095

//so:extern SDLK_MEDIA_PREVIOUS_TRACK
const KeyMEDIA_PREVIOUS_TRACK = 1073742092

//so:extern SDLK_MEDIA_RECORD
const KeyMEDIA_RECORD = 1073742088

//so:extern SDLK_MEDIA_REWIND
const KeyMEDIA_REWIND = 1073742090

//so:extern SDLK_MEDIA_SELECT
const KeyMEDIA_SELECT = 1073742096

//so:extern SDLK_MEDIA_STOP
const KeyMEDIA_STOP = 1073742093

//so:extern SDLK_MENU
const KeyMENU = 1073741942

//so:extern SDLK_MINUS
const KeyMINUS = 45

//so:extern SDLK_MODE
const KeyMODE = 1073742081

//so:extern SDLK_MULTI_KEY_COMPOSE
const KeyMULTI_KEY_COMPOSE = 536870915

//so:extern SDLK_MUTE
const KeyMUTE = 1073741951

//so:extern SDLK_N
const KeyN = 110

//so:extern SDLK_NUMLOCKCLEAR
const KeyNUMLOCKCLEAR = 1073741907

//so:extern SDLK_O
const KeyO = 111

//so:extern SDLK_OPER
const KeyOPER = 1073741985

//so:extern SDLK_OUT
const KeyOUT = 1073741984

//so:extern SDLK_P
const KeyP = 112

//so:extern SDLK_PAGEDOWN
const KeyPAGEDOWN = 1073741902

//so:extern SDLK_PAGEUP
const KeyPAGEUP = 1073741899

//so:extern SDLK_PASTE
const KeyPASTE = 1073741949

//so:extern SDLK_PAUSE
const KeyPAUSE = 1073741896

//so:extern SDLK_PERCENT
const KeyPERCENT = 37

//so:extern SDLK_PERIOD
const KeyPERIOD = 46

//so:extern SDLK_PIPE
const KeyPIPE = 124

//so:extern SDLK_PLUS
const KeyPLUS = 43

//so:extern SDLK_PLUSMINUS
const KeyPLUSMINUS = 177

//so:extern SDLK_POWER
const KeyPOWER = 1073741926

//so:extern SDLK_PRINTSCREEN
const KeyPRINTSCREEN = 1073741894

//so:extern SDLK_PRIOR
const KeyPRIOR = 1073741981

//so:extern SDLK_Q
const KeyQ = 113

//so:extern SDLK_QUESTION
const KeyQUESTION = 63

//so:extern SDLK_R
const KeyR = 114

//so:extern SDLK_RALT
const KeyRALT = 1073742054

//so:extern SDLK_RCTRL
const KeyRCTRL = 1073742052

//so:extern SDLK_RETURN
const KeyRETURN = 13

//so:extern SDLK_RETURN2
const KeyRETURN2 = 1073741982

//so:extern SDLK_RGUI
const KeyRGUI = 1073742055

//so:extern SDLK_RHYPER
const KeyRHYPER = 536870919

//so:extern SDLK_RIGHT
const KeyRIGHT = 1073741903

//so:extern SDLK_RIGHTBRACE
const KeyRIGHTBRACE = 125

//so:extern SDLK_RIGHTBRACKET
const KeyRIGHTBRACKET = 93

//so:extern SDLK_RIGHTPAREN
const KeyRIGHTPAREN = 41

//so:extern SDLK_RMETA
const KeyRMETA = 536870917

//so:extern SDLK_RSHIFT
const KeyRSHIFT = 1073742053

//so:extern SDLK_S
const KeyS = 115

//so:extern SDLK_SCANCODE_MASK
const KeySCANCODE_MASK = 1073741824

//so:extern SDLK_SCROLLLOCK
const KeySCROLLLOCK = 1073741895

//so:extern SDLK_SELECT
const KeySELECT = 1073741943

//so:extern SDLK_SEMICOLON
const KeySEMICOLON = 59

//so:extern SDLK_SEPARATOR
const KeySEPARATOR = 1073741983

//so:extern SDLK_SLASH
const KeySLASH = 47

//so:extern SDLK_SLEEP
const KeySLEEP = 1073742082

//so:extern SDLK_SOFTLEFT
const KeySOFTLEFT = 1073742111

//so:extern SDLK_SOFTRIGHT
const KeySOFTRIGHT = 1073742112

//so:extern SDLK_SPACE
const KeySPACE = 32

//so:extern SDLK_STOP
const KeySTOP = 1073741944

//so:extern SDLK_SYSREQ
const KeySYSREQ = 1073741978

//so:extern SDLK_T
const KeyT = 116

//so:extern SDLK_TAB
const KeyTAB = 9

//so:extern SDLK_THOUSANDSSEPARATOR
const KeyTHOUSANDSSEPARATOR = 1073742002

//so:extern SDLK_TILDE
const KeyTILDE = 126

//so:extern SDLK_U
const KeyU = 117

//so:extern SDLK_UNDERSCORE
const KeyUNDERSCORE = 95

//so:extern SDLK_UNDO
const KeyUNDO = 1073741946

//so:extern SDLK_UNKNOWN
const KeyUNKNOWN = 0

//so:extern SDLK_UP
const KeyUP = 1073741906

//so:extern SDLK_V
const KeyV = 118

//so:extern SDLK_VOLUMEDOWN
const KeyVOLUMEDOWN = 1073741953

//so:extern SDLK_VOLUMEUP
const KeyVOLUMEUP = 1073741952

//so:extern SDLK_W
const KeyW = 119

//so:extern SDLK_WAKE
const KeyWAKE = 1073742083

//so:extern SDLK_X
const KeyX = 120

//so:extern SDLK_Y
const KeyY = 121

//so:extern SDLK_Z
const KeyZ = 122
