// GENERATED BY cmd/assetIDgen/main.go DO NOT EDIT.

package assets

type ID uint32 // ID that maps to a path inside the assets folder.

const (
	_ ID = iota

	Armor_chain_1 /* /armor/chain_1.png */

	Armor_chain_2 /* /armor/chain_2.png */

	Armor_cloth_1 /* /armor/cloth_1.png */

	Armor_cloth_2 /* /armor/cloth_2.png */

	Armor_diamond_1 /* /armor/diamond_1.png */

	Armor_diamond_2 /* /armor/diamond_2.png */

	Armor_gold_1 /* /armor/gold_1.png */

	Armor_gold_2 /* /armor/gold_2.png */

	Armor_iron_1 /* /armor/iron_1.png */

	Armor_iron_2 /* /armor/iron_2.png */

	Armor_power /* /armor/power.png */

	Art_kz /* /art/kz.png */

	Environment_clouds /* /environment/clouds.png */

	Environment_rain /* /environment/rain.png */

	Environment_snow /* /environment/snow.png */

	Font_default /* /font/default.png */

	Gui_background /* /gui/background.png */

	Gui_container /* /gui/container.png */

	Gui_crafting /* /gui/crafting.png */

	Gui_furnace /* /gui/furnace.png */

	Gui_gui /* /gui/gui.png */

	Gui_icons /* /gui/icons.png */

	Gui_inventory /* /gui/inventory.png */

	Gui_items /* /gui/items.png */

	Gui_logo /* /gui/logo.png */

	Gui_particles /* /gui/particles.png */

	Gui_slot /* /gui/slot.png */

	Gui_trap /* /gui/trap.png */

	Gui_unknown_pack /* /gui/unknown_pack.png */

	Icon /* /icon.png */

	Icons_icon_16x16 /* /icons/icon_16x16.png */

	Icons_icon_32x32 /* /icons/icon_32x32.png */

	Item_arrows /* /item/arrows.png */

	Item_boat /* /item/boat.png */

	Item_cart /* /item/cart.png */

	Item_door /* /item/door.png */

	Item_sign /* /item/sign.png */

	Misc_dial /* /misc/dial.png */

	Misc_foliagecolor /* /misc/foliagecolor.png */

	Misc_footprint /* /misc/footprint.png */

	Misc_grasscolor /* /misc/grasscolor.png */

	Misc_mapbg /* /misc/mapbg.png */

	Misc_mapicons /* /misc/mapicons.png */

	Misc_pumpkinblur /* /misc/pumpkinblur.png */

	Misc_shadow /* /misc/shadow.png */

	Misc_vignette /* /misc/vignette.png */

	Misc_water /* /misc/water.png */

	Misc_watercolor /* /misc/watercolor.png */

	Mob_char /* /mob/char.png */

	Mob_chicken /* /mob/chicken.png */

	Mob_cow /* /mob/cow.png */

	Mob_creeper /* /mob/creeper.png */

	Mob_ghast /* /mob/ghast.png */

	Mob_ghast_fire /* /mob/ghast_fire.png */

	Mob_pig /* /mob/pig.png */

	Mob_pigman /* /mob/pigman.png */

	Mob_pigzombie /* /mob/pigzombie.png */

	Mob_saddle /* /mob/saddle.png */

	Mob_sheep /* /mob/sheep.png */

	Mob_sheep_fur /* /mob/sheep_fur.png */

	Mob_silverfish /* /mob/silverfish.png */

	Mob_skeleton /* /mob/skeleton.png */

	Mob_slime /* /mob/slime.png */

	Mob_spider /* /mob/spider.png */

	Mob_spider_eyes /* /mob/spider_eyes.png */

	Mob_squid /* /mob/squid.png */

	Mob_wolf /* /mob/wolf.png */

	Mob_wolf_angry /* /mob/wolf_angry.png */

	Mob_wolf_tame /* /mob/wolf_tame.png */

	Mob_zombie /* /mob/zombie.png */

	Music_calm1 /* /music/calm1.ogg */

	Music_calm2 /* /music/calm2.ogg */

	Music_calm3 /* /music/calm3.ogg */

	Newmusic_hal1 /* /newmusic/hal1.ogg */

	Newmusic_hal2 /* /newmusic/hal2.ogg */

	Newmusic_hal3 /* /newmusic/hal3.ogg */

	Newmusic_hal4 /* /newmusic/hal4.ogg */

	Newmusic_nuance1 /* /newmusic/nuance1.ogg */

	Newmusic_nuance2 /* /newmusic/nuance2.ogg */

	Newmusic_piano1 /* /newmusic/piano1.ogg */

	Newmusic_piano2 /* /newmusic/piano2.ogg */

	Newmusic_piano3 /* /newmusic/piano3.ogg */

	Newsound_ambient_cave_cave1 /* /newsound/ambient/cave/cave1.ogg */

	Newsound_ambient_cave_cave10 /* /newsound/ambient/cave/cave10.ogg */

	Newsound_ambient_cave_cave11 /* /newsound/ambient/cave/cave11.ogg */

	Newsound_ambient_cave_cave12 /* /newsound/ambient/cave/cave12.ogg */

	Newsound_ambient_cave_cave13 /* /newsound/ambient/cave/cave13.ogg */

	Newsound_ambient_cave_cave2 /* /newsound/ambient/cave/cave2.ogg */

	Newsound_ambient_cave_cave3 /* /newsound/ambient/cave/cave3.ogg */

	Newsound_ambient_cave_cave4 /* /newsound/ambient/cave/cave4.ogg */

	Newsound_ambient_cave_cave5 /* /newsound/ambient/cave/cave5.ogg */

	Newsound_ambient_cave_cave6 /* /newsound/ambient/cave/cave6.ogg */

	Newsound_ambient_cave_cave7 /* /newsound/ambient/cave/cave7.ogg */

	Newsound_ambient_cave_cave8 /* /newsound/ambient/cave/cave8.ogg */

	Newsound_ambient_cave_cave9 /* /newsound/ambient/cave/cave9.ogg */

	Newsound_ambient_weather_rain1 /* /newsound/ambient/weather/rain1.ogg */

	Newsound_ambient_weather_rain2 /* /newsound/ambient/weather/rain2.ogg */

	Newsound_ambient_weather_rain3 /* /newsound/ambient/weather/rain3.ogg */

	Newsound_ambient_weather_rain4 /* /newsound/ambient/weather/rain4.ogg */

	Newsound_ambient_weather_thunder1 /* /newsound/ambient/weather/thunder1.ogg */

	Newsound_ambient_weather_thunder2 /* /newsound/ambient/weather/thunder2.ogg */

	Newsound_ambient_weather_thunder3 /* /newsound/ambient/weather/thunder3.ogg */

	Newsound_damage_fallbig1 /* /newsound/damage/fallbig1.ogg */

	Newsound_damage_fallbig2 /* /newsound/damage/fallbig2.ogg */

	Newsound_damage_fallsmall /* /newsound/damage/fallsmall.ogg */

	Newsound_damage_hurtflesh1 /* /newsound/damage/hurtflesh1.ogg */

	Newsound_damage_hurtflesh2 /* /newsound/damage/hurtflesh2.ogg */

	Newsound_damage_hurtflesh3 /* /newsound/damage/hurtflesh3.ogg */

	Newsound_fire_fire /* /newsound/fire/fire.ogg */

	Newsound_fire_ignite /* /newsound/fire/ignite.ogg */

	Newsound_liquid_lava /* /newsound/liquid/lava.ogg */

	Newsound_liquid_lavapop /* /newsound/liquid/lavapop.ogg */

	Newsound_liquid_splash /* /newsound/liquid/splash.ogg */

	Newsound_liquid_water /* /newsound/liquid/water.ogg */

	Newsound_mob_blaze_breathe1 /* /newsound/mob/blaze/breathe1.ogg */

	Newsound_mob_blaze_breathe2 /* /newsound/mob/blaze/breathe2.ogg */

	Newsound_mob_blaze_breathe3 /* /newsound/mob/blaze/breathe3.ogg */

	Newsound_mob_blaze_breathe4 /* /newsound/mob/blaze/breathe4.ogg */

	Newsound_mob_blaze_death /* /newsound/mob/blaze/death.ogg */

	Newsound_mob_blaze_hit1 /* /newsound/mob/blaze/hit1.ogg */

	Newsound_mob_blaze_hit2 /* /newsound/mob/blaze/hit2.ogg */

	Newsound_mob_blaze_hit3 /* /newsound/mob/blaze/hit3.ogg */

	Newsound_mob_blaze_hit4 /* /newsound/mob/blaze/hit4.ogg */

	Newsound_mob_cat_hiss1 /* /newsound/mob/cat/hiss1.ogg */

	Newsound_mob_cat_hiss2 /* /newsound/mob/cat/hiss2.ogg */

	Newsound_mob_cat_hiss3 /* /newsound/mob/cat/hiss3.ogg */

	Newsound_mob_cat_hitt1 /* /newsound/mob/cat/hitt1.ogg */

	Newsound_mob_cat_hitt2 /* /newsound/mob/cat/hitt2.ogg */

	Newsound_mob_cat_hitt3 /* /newsound/mob/cat/hitt3.ogg */

	Newsound_mob_cat_meow1 /* /newsound/mob/cat/meow1.ogg */

	Newsound_mob_cat_meow2 /* /newsound/mob/cat/meow2.ogg */

	Newsound_mob_cat_meow3 /* /newsound/mob/cat/meow3.ogg */

	Newsound_mob_cat_meow4 /* /newsound/mob/cat/meow4.ogg */

	Newsound_mob_cat_purr1 /* /newsound/mob/cat/purr1.ogg */

	Newsound_mob_cat_purr2 /* /newsound/mob/cat/purr2.ogg */

	Newsound_mob_cat_purr3 /* /newsound/mob/cat/purr3.ogg */

	Newsound_mob_cat_purreow1 /* /newsound/mob/cat/purreow1.ogg */

	Newsound_mob_cat_purreow2 /* /newsound/mob/cat/purreow2.ogg */

	Newsound_mob_chicken1 /* /newsound/mob/chicken1.ogg */

	Newsound_mob_chicken2 /* /newsound/mob/chicken2.ogg */

	Newsound_mob_chicken3 /* /newsound/mob/chicken3.ogg */

	Newsound_mob_chickenhurt1 /* /newsound/mob/chickenhurt1.ogg */

	Newsound_mob_chickenhurt2 /* /newsound/mob/chickenhurt2.ogg */

	Newsound_mob_chickenplop /* /newsound/mob/chickenplop.ogg */

	Newsound_mob_cow1 /* /newsound/mob/cow1.ogg */

	Newsound_mob_cow2 /* /newsound/mob/cow2.ogg */

	Newsound_mob_cow3 /* /newsound/mob/cow3.ogg */

	Newsound_mob_cow4 /* /newsound/mob/cow4.ogg */

	Newsound_mob_cowhurt1 /* /newsound/mob/cowhurt1.ogg */

	Newsound_mob_cowhurt2 /* /newsound/mob/cowhurt2.ogg */

	Newsound_mob_cowhurt3 /* /newsound/mob/cowhurt3.ogg */

	Newsound_mob_creeper1 /* /newsound/mob/creeper1.ogg */

	Newsound_mob_creeper2 /* /newsound/mob/creeper2.ogg */

	Newsound_mob_creeper3 /* /newsound/mob/creeper3.ogg */

	Newsound_mob_creeper4 /* /newsound/mob/creeper4.ogg */

	Newsound_mob_creeperdeath /* /newsound/mob/creeperdeath.ogg */

	Newsound_mob_endermen_death /* /newsound/mob/endermen/death.ogg */

	Newsound_mob_endermen_hit1 /* /newsound/mob/endermen/hit1.ogg */

	Newsound_mob_endermen_hit2 /* /newsound/mob/endermen/hit2.ogg */

	Newsound_mob_endermen_hit3 /* /newsound/mob/endermen/hit3.ogg */

	Newsound_mob_endermen_hit4 /* /newsound/mob/endermen/hit4.ogg */

	Newsound_mob_endermen_idle1 /* /newsound/mob/endermen/idle1.ogg */

	Newsound_mob_endermen_idle2 /* /newsound/mob/endermen/idle2.ogg */

	Newsound_mob_endermen_idle3 /* /newsound/mob/endermen/idle3.ogg */

	Newsound_mob_endermen_idle4 /* /newsound/mob/endermen/idle4.ogg */

	Newsound_mob_endermen_idle5 /* /newsound/mob/endermen/idle5.ogg */

	Newsound_mob_endermen_portal /* /newsound/mob/endermen/portal.ogg */

	Newsound_mob_endermen_portal2 /* /newsound/mob/endermen/portal2.ogg */

	Newsound_mob_endermen_scream1 /* /newsound/mob/endermen/scream1.ogg */

	Newsound_mob_endermen_scream2 /* /newsound/mob/endermen/scream2.ogg */

	Newsound_mob_endermen_scream3 /* /newsound/mob/endermen/scream3.ogg */

	Newsound_mob_endermen_scream4 /* /newsound/mob/endermen/scream4.ogg */

	Newsound_mob_endermen_stare /* /newsound/mob/endermen/stare.ogg */

	Newsound_mob_ghast_affectionate_scream /* /newsound/mob/ghast/affectionate scream.ogg */

	Newsound_mob_ghast_charge /* /newsound/mob/ghast/charge.ogg */

	Newsound_mob_ghast_death /* /newsound/mob/ghast/death.ogg */

	Newsound_mob_ghast_fireball4 /* /newsound/mob/ghast/fireball4.ogg */

	Newsound_mob_ghast_moan1 /* /newsound/mob/ghast/moan1.ogg */

	Newsound_mob_ghast_moan2 /* /newsound/mob/ghast/moan2.ogg */

	Newsound_mob_ghast_moan3 /* /newsound/mob/ghast/moan3.ogg */

	Newsound_mob_ghast_moan4 /* /newsound/mob/ghast/moan4.ogg */

	Newsound_mob_ghast_moan5 /* /newsound/mob/ghast/moan5.ogg */

	Newsound_mob_ghast_moan6 /* /newsound/mob/ghast/moan6.ogg */

	Newsound_mob_ghast_moan7 /* /newsound/mob/ghast/moan7.ogg */

	Newsound_mob_ghast_scream1 /* /newsound/mob/ghast/scream1.ogg */

	Newsound_mob_ghast_scream2 /* /newsound/mob/ghast/scream2.ogg */

	Newsound_mob_ghast_scream3 /* /newsound/mob/ghast/scream3.ogg */

	Newsound_mob_ghast_scream4 /* /newsound/mob/ghast/scream4.ogg */

	Newsound_mob_ghast_scream5 /* /newsound/mob/ghast/scream5.ogg */

	Newsound_mob_irongolem_death /* /newsound/mob/irongolem/death.ogg */

	Newsound_mob_irongolem_hit1 /* /newsound/mob/irongolem/hit1.ogg */

	Newsound_mob_irongolem_hit2 /* /newsound/mob/irongolem/hit2.ogg */

	Newsound_mob_irongolem_hit3 /* /newsound/mob/irongolem/hit3.ogg */

	Newsound_mob_irongolem_hit4 /* /newsound/mob/irongolem/hit4.ogg */

	Newsound_mob_irongolem_throw /* /newsound/mob/irongolem/throw.ogg */

	Newsound_mob_irongolem_walk1 /* /newsound/mob/irongolem/walk1.ogg */

	Newsound_mob_irongolem_walk2 /* /newsound/mob/irongolem/walk2.ogg */

	Newsound_mob_irongolem_walk3 /* /newsound/mob/irongolem/walk3.ogg */

	Newsound_mob_irongolem_walk4 /* /newsound/mob/irongolem/walk4.ogg */

	Newsound_mob_magmacube_big1 /* /newsound/mob/magmacube/big1.ogg */

	Newsound_mob_magmacube_big2 /* /newsound/mob/magmacube/big2.ogg */

	Newsound_mob_magmacube_big3 /* /newsound/mob/magmacube/big3.ogg */

	Newsound_mob_magmacube_big4 /* /newsound/mob/magmacube/big4.ogg */

	Newsound_mob_magmacube_jump1 /* /newsound/mob/magmacube/jump1.ogg */

	Newsound_mob_magmacube_jump2 /* /newsound/mob/magmacube/jump2.ogg */

	Newsound_mob_magmacube_jump3 /* /newsound/mob/magmacube/jump3.ogg */

	Newsound_mob_magmacube_jump4 /* /newsound/mob/magmacube/jump4.ogg */

	Newsound_mob_magmacube_small1 /* /newsound/mob/magmacube/small1.ogg */

	Newsound_mob_magmacube_small2 /* /newsound/mob/magmacube/small2.ogg */

	Newsound_mob_magmacube_small3 /* /newsound/mob/magmacube/small3.ogg */

	Newsound_mob_magmacube_small4 /* /newsound/mob/magmacube/small4.ogg */

	Newsound_mob_magmacube_small5 /* /newsound/mob/magmacube/small5.ogg */

	Newsound_mob_pig1 /* /newsound/mob/pig1.ogg */

	Newsound_mob_pig2 /* /newsound/mob/pig2.ogg */

	Newsound_mob_pig3 /* /newsound/mob/pig3.ogg */

	Newsound_mob_pigdeath /* /newsound/mob/pigdeath.ogg */

	Newsound_mob_sheep1 /* /newsound/mob/sheep1.ogg */

	Newsound_mob_sheep2 /* /newsound/mob/sheep2.ogg */

	Newsound_mob_sheep3 /* /newsound/mob/sheep3.ogg */

	Newsound_mob_silverfish_hit1 /* /newsound/mob/silverfish/hit1.ogg */

	Newsound_mob_silverfish_hit2 /* /newsound/mob/silverfish/hit2.ogg */

	Newsound_mob_silverfish_hit3 /* /newsound/mob/silverfish/hit3.ogg */

	Newsound_mob_silverfish_kill /* /newsound/mob/silverfish/kill.ogg */

	Newsound_mob_silverfish_say1 /* /newsound/mob/silverfish/say1.ogg */

	Newsound_mob_silverfish_say2 /* /newsound/mob/silverfish/say2.ogg */

	Newsound_mob_silverfish_say3 /* /newsound/mob/silverfish/say3.ogg */

	Newsound_mob_silverfish_say4 /* /newsound/mob/silverfish/say4.ogg */

	Newsound_mob_silverfish_step1 /* /newsound/mob/silverfish/step1.ogg */

	Newsound_mob_silverfish_step2 /* /newsound/mob/silverfish/step2.ogg */

	Newsound_mob_silverfish_step3 /* /newsound/mob/silverfish/step3.ogg */

	Newsound_mob_silverfish_step4 /* /newsound/mob/silverfish/step4.ogg */

	Newsound_mob_skeleton1 /* /newsound/mob/skeleton1.ogg */

	Newsound_mob_skeleton2 /* /newsound/mob/skeleton2.ogg */

	Newsound_mob_skeleton3 /* /newsound/mob/skeleton3.ogg */

	Newsound_mob_skeletondeath /* /newsound/mob/skeletondeath.ogg */

	Newsound_mob_skeletonhurt1 /* /newsound/mob/skeletonhurt1.ogg */

	Newsound_mob_skeletonhurt2 /* /newsound/mob/skeletonhurt2.ogg */

	Newsound_mob_skeletonhurt3 /* /newsound/mob/skeletonhurt3.ogg */

	Newsound_mob_skeletonhurt4 /* /newsound/mob/skeletonhurt4.ogg */

	Newsound_mob_slime1 /* /newsound/mob/slime1.ogg */

	Newsound_mob_slime2 /* /newsound/mob/slime2.ogg */

	Newsound_mob_slime3 /* /newsound/mob/slime3.ogg */

	Newsound_mob_slime4 /* /newsound/mob/slime4.ogg */

	Newsound_mob_slime5 /* /newsound/mob/slime5.ogg */

	Newsound_mob_slimeattack1 /* /newsound/mob/slimeattack1.ogg */

	Newsound_mob_slimeattack2 /* /newsound/mob/slimeattack2.ogg */

	Newsound_mob_spider1 /* /newsound/mob/spider1.ogg */

	Newsound_mob_spider2 /* /newsound/mob/spider2.ogg */

	Newsound_mob_spider3 /* /newsound/mob/spider3.ogg */

	Newsound_mob_spider4 /* /newsound/mob/spider4.ogg */

	Newsound_mob_spiderdeath /* /newsound/mob/spiderdeath.ogg */

	Newsound_mob_wolf_bark1 /* /newsound/mob/wolf/bark1.ogg */

	Newsound_mob_wolf_bark2 /* /newsound/mob/wolf/bark2.ogg */

	Newsound_mob_wolf_bark3 /* /newsound/mob/wolf/bark3.ogg */

	Newsound_mob_wolf_death /* /newsound/mob/wolf/death.ogg */

	Newsound_mob_wolf_growl1 /* /newsound/mob/wolf/growl1.ogg */

	Newsound_mob_wolf_growl2 /* /newsound/mob/wolf/growl2.ogg */

	Newsound_mob_wolf_growl3 /* /newsound/mob/wolf/growl3.ogg */

	Newsound_mob_wolf_howl1 /* /newsound/mob/wolf/howl1.ogg */

	Newsound_mob_wolf_howl2 /* /newsound/mob/wolf/howl2.ogg */

	Newsound_mob_wolf_hurt1 /* /newsound/mob/wolf/hurt1.ogg */

	Newsound_mob_wolf_hurt2 /* /newsound/mob/wolf/hurt2.ogg */

	Newsound_mob_wolf_hurt3 /* /newsound/mob/wolf/hurt3.ogg */

	Newsound_mob_wolf_panting /* /newsound/mob/wolf/panting.ogg */

	Newsound_mob_wolf_shake /* /newsound/mob/wolf/shake.ogg */

	Newsound_mob_wolf_whine /* /newsound/mob/wolf/whine.ogg */

	Newsound_mob_zombie_metal1 /* /newsound/mob/zombie/metal1.ogg */

	Newsound_mob_zombie_metal2 /* /newsound/mob/zombie/metal2.ogg */

	Newsound_mob_zombie_metal3 /* /newsound/mob/zombie/metal3.ogg */

	Newsound_mob_zombie_wood1 /* /newsound/mob/zombie/wood1.ogg */

	Newsound_mob_zombie_wood2 /* /newsound/mob/zombie/wood2.ogg */

	Newsound_mob_zombie_wood3 /* /newsound/mob/zombie/wood3.ogg */

	Newsound_mob_zombie_wood4 /* /newsound/mob/zombie/wood4.ogg */

	Newsound_mob_zombie_woodbreak /* /newsound/mob/zombie/woodbreak.ogg */

	Newsound_mob_zombie1 /* /newsound/mob/zombie1.ogg */

	Newsound_mob_zombie2 /* /newsound/mob/zombie2.ogg */

	Newsound_mob_zombie3 /* /newsound/mob/zombie3.ogg */

	Newsound_mob_zombiedeath /* /newsound/mob/zombiedeath.ogg */

	Newsound_mob_zombiehurt1 /* /newsound/mob/zombiehurt1.ogg */

	Newsound_mob_zombiehurt2 /* /newsound/mob/zombiehurt2.ogg */

	Newsound_mob_zombiepig_zpig1 /* /newsound/mob/zombiepig/zpig1.ogg */

	Newsound_mob_zombiepig_zpig2 /* /newsound/mob/zombiepig/zpig2.ogg */

	Newsound_mob_zombiepig_zpig3 /* /newsound/mob/zombiepig/zpig3.ogg */

	Newsound_mob_zombiepig_zpig4 /* /newsound/mob/zombiepig/zpig4.ogg */

	Newsound_mob_zombiepig_zpigangry1 /* /newsound/mob/zombiepig/zpigangry1.ogg */

	Newsound_mob_zombiepig_zpigangry2 /* /newsound/mob/zombiepig/zpigangry2.ogg */

	Newsound_mob_zombiepig_zpigangry3 /* /newsound/mob/zombiepig/zpigangry3.ogg */

	Newsound_mob_zombiepig_zpigangry4 /* /newsound/mob/zombiepig/zpigangry4.ogg */

	Newsound_mob_zombiepig_zpigdeath /* /newsound/mob/zombiepig/zpigdeath.ogg */

	Newsound_mob_zombiepig_zpighurt1 /* /newsound/mob/zombiepig/zpighurt1.ogg */

	Newsound_mob_zombiepig_zpighurt2 /* /newsound/mob/zombiepig/zpighurt2.ogg */

	Newsound_note_bass /* /newsound/note/bass.ogg */

	Newsound_note_bassattack /* /newsound/note/bassattack.ogg */

	Newsound_note_bd /* /newsound/note/bd.ogg */

	Newsound_note_harp /* /newsound/note/harp.ogg */

	Newsound_note_hat /* /newsound/note/hat.ogg */

	Newsound_note_pling /* /newsound/note/pling.ogg */

	Newsound_note_snare /* /newsound/note/snare.ogg */

	Newsound_portal_portal /* /newsound/portal/portal.ogg */

	Newsound_portal_travel /* /newsound/portal/travel.ogg */

	Newsound_portal_trigger /* /newsound/portal/trigger.ogg */

	Newsound_random_bow /* /newsound/random/bow.ogg */

	Newsound_random_bowhit1 /* /newsound/random/bowhit1.ogg */

	Newsound_random_bowhit2 /* /newsound/random/bowhit2.ogg */

	Newsound_random_bowhit3 /* /newsound/random/bowhit3.ogg */

	Newsound_random_bowhit4 /* /newsound/random/bowhit4.ogg */

	Newsound_random_break /* /newsound/random/break.ogg */

	Newsound_random_breath /* /newsound/random/breath.ogg */

	Newsound_random_burp /* /newsound/random/burp.ogg */

	Newsound_random_chestclosed /* /newsound/random/chestclosed.ogg */

	Newsound_random_chestopen /* /newsound/random/chestopen.ogg */

	Newsound_random_click /* /newsound/random/click.ogg */

	Newsound_random_door_close /* /newsound/random/door_close.ogg */

	Newsound_random_door_open /* /newsound/random/door_open.ogg */

	Newsound_random_drink /* /newsound/random/drink.ogg */

	Newsound_random_drr /* /newsound/random/drr.ogg */

	Newsound_random_eat1 /* /newsound/random/eat1.ogg */

	Newsound_random_eat2 /* /newsound/random/eat2.ogg */

	Newsound_random_eat3 /* /newsound/random/eat3.ogg */

	Newsound_random_explode1 /* /newsound/random/explode1.ogg */

	Newsound_random_explode2 /* /newsound/random/explode2.ogg */

	Newsound_random_explode3 /* /newsound/random/explode3.ogg */

	Newsound_random_explode4 /* /newsound/random/explode4.ogg */

	Newsound_random_fizz /* /newsound/random/fizz.ogg */

	Newsound_random_fuse /* /newsound/random/fuse.ogg */

	Newsound_random_glass1 /* /newsound/random/glass1.ogg */

	Newsound_random_glass2 /* /newsound/random/glass2.ogg */

	Newsound_random_glass3 /* /newsound/random/glass3.ogg */

	Newsound_random_hurt /* /newsound/random/hurt.ogg */

	Newsound_random_levelup /* /newsound/random/levelup.ogg */

	Newsound_random_old_explode /* /newsound/random/old_explode.ogg */

	Newsound_random_orb /* /newsound/random/orb.ogg */

	Newsound_random_pop /* /newsound/random/pop.ogg */

	Newsound_random_splash /* /newsound/random/splash.ogg */

	Newsound_random_wood_click /* /newsound/random/wood click.ogg */

	Newsound_step_cloth1 /* /newsound/step/cloth1.ogg */

	Newsound_step_cloth2 /* /newsound/step/cloth2.ogg */

	Newsound_step_cloth3 /* /newsound/step/cloth3.ogg */

	Newsound_step_cloth4 /* /newsound/step/cloth4.ogg */

	Newsound_step_grass1 /* /newsound/step/grass1.ogg */

	Newsound_step_grass2 /* /newsound/step/grass2.ogg */

	Newsound_step_grass3 /* /newsound/step/grass3.ogg */

	Newsound_step_grass4 /* /newsound/step/grass4.ogg */

	Newsound_step_gravel1 /* /newsound/step/gravel1.ogg */

	Newsound_step_gravel2 /* /newsound/step/gravel2.ogg */

	Newsound_step_gravel3 /* /newsound/step/gravel3.ogg */

	Newsound_step_gravel4 /* /newsound/step/gravel4.ogg */

	Newsound_step_sand1 /* /newsound/step/sand1.ogg */

	Newsound_step_sand2 /* /newsound/step/sand2.ogg */

	Newsound_step_sand3 /* /newsound/step/sand3.ogg */

	Newsound_step_sand4 /* /newsound/step/sand4.ogg */

	Newsound_step_snow1 /* /newsound/step/snow1.ogg */

	Newsound_step_snow2 /* /newsound/step/snow2.ogg */

	Newsound_step_snow3 /* /newsound/step/snow3.ogg */

	Newsound_step_snow4 /* /newsound/step/snow4.ogg */

	Newsound_step_stone1 /* /newsound/step/stone1.ogg */

	Newsound_step_stone2 /* /newsound/step/stone2.ogg */

	Newsound_step_stone3 /* /newsound/step/stone3.ogg */

	Newsound_step_stone4 /* /newsound/step/stone4.ogg */

	Newsound_step_wood1 /* /newsound/step/wood1.ogg */

	Newsound_step_wood2 /* /newsound/step/wood2.ogg */

	Newsound_step_wood3 /* /newsound/step/wood3.ogg */

	Newsound_step_wood4 /* /newsound/step/wood4.ogg */

	Newsound_tile_piston_in /* /newsound/tile/piston/in.ogg */

	Newsound_tile_piston_out /* /newsound/tile/piston/out.ogg */

	Pack /* /pack.png */

	Particles /* /particles.png */

	Pe_humble /* /pe/humble.png */

	Sound_step_grass1 /* /sound/step/grass1.ogg */

	Sound_step_grass2 /* /sound/step/grass2.ogg */

	Sound_step_grass3 /* /sound/step/grass3.ogg */

	Sound_step_grass4 /* /sound/step/grass4.ogg */

	Sound_step_gravel1 /* /sound/step/gravel1.ogg */

	Sound_step_gravel2 /* /sound/step/gravel2.ogg */

	Sound_step_gravel3 /* /sound/step/gravel3.ogg */

	Sound_step_gravel4 /* /sound/step/gravel4.ogg */

	Sound_step_stone1 /* /sound/step/stone1.ogg */

	Sound_step_stone2 /* /sound/step/stone2.ogg */

	Sound_step_stone3 /* /sound/step/stone3.ogg */

	Sound_step_stone4 /* /sound/step/stone4.ogg */

	Sound_step_wood1 /* /sound/step/wood1.ogg */

	Sound_step_wood2 /* /sound/step/wood2.ogg */

	Sound_step_wood3 /* /sound/step/wood3.ogg */

	Sound_step_wood4 /* /sound/step/wood4.ogg */

	Sound3_ambient_cave_cave1 /* /sound3/ambient/cave/cave1.ogg */

	Sound3_ambient_cave_cave10 /* /sound3/ambient/cave/cave10.ogg */

	Sound3_ambient_cave_cave11 /* /sound3/ambient/cave/cave11.ogg */

	Sound3_ambient_cave_cave12 /* /sound3/ambient/cave/cave12.ogg */

	Sound3_ambient_cave_cave13 /* /sound3/ambient/cave/cave13.ogg */

	Sound3_ambient_cave_cave2 /* /sound3/ambient/cave/cave2.ogg */

	Sound3_ambient_cave_cave3 /* /sound3/ambient/cave/cave3.ogg */

	Sound3_ambient_cave_cave4 /* /sound3/ambient/cave/cave4.ogg */

	Sound3_ambient_cave_cave5 /* /sound3/ambient/cave/cave5.ogg */

	Sound3_ambient_cave_cave6 /* /sound3/ambient/cave/cave6.ogg */

	Sound3_ambient_cave_cave7 /* /sound3/ambient/cave/cave7.ogg */

	Sound3_ambient_cave_cave8 /* /sound3/ambient/cave/cave8.ogg */

	Sound3_ambient_cave_cave9 /* /sound3/ambient/cave/cave9.ogg */

	Sound3_ambient_weather_rain1 /* /sound3/ambient/weather/rain1.ogg */

	Sound3_ambient_weather_rain2 /* /sound3/ambient/weather/rain2.ogg */

	Sound3_ambient_weather_rain3 /* /sound3/ambient/weather/rain3.ogg */

	Sound3_ambient_weather_rain4 /* /sound3/ambient/weather/rain4.ogg */

	Sound3_ambient_weather_thunder1 /* /sound3/ambient/weather/thunder1.ogg */

	Sound3_ambient_weather_thunder2 /* /sound3/ambient/weather/thunder2.ogg */

	Sound3_ambient_weather_thunder3 /* /sound3/ambient/weather/thunder3.ogg */

	Sound3_damage_fallbig /* /sound3/damage/fallbig.ogg */

	Sound3_damage_fallsmall /* /sound3/damage/fallsmall.ogg */

	Sound3_damage_hit1 /* /sound3/damage/hit1.ogg */

	Sound3_damage_hit2 /* /sound3/damage/hit2.ogg */

	Sound3_damage_hit3 /* /sound3/damage/hit3.ogg */

	Sound3_dig_cloth1 /* /sound3/dig/cloth1.ogg */

	Sound3_dig_cloth2 /* /sound3/dig/cloth2.ogg */

	Sound3_dig_cloth3 /* /sound3/dig/cloth3.ogg */

	Sound3_dig_cloth4 /* /sound3/dig/cloth4.ogg */

	Sound3_dig_grass1 /* /sound3/dig/grass1.ogg */

	Sound3_dig_grass2 /* /sound3/dig/grass2.ogg */

	Sound3_dig_grass3 /* /sound3/dig/grass3.ogg */

	Sound3_dig_grass4 /* /sound3/dig/grass4.ogg */

	Sound3_dig_gravel1 /* /sound3/dig/gravel1.ogg */

	Sound3_dig_gravel2 /* /sound3/dig/gravel2.ogg */

	Sound3_dig_gravel3 /* /sound3/dig/gravel3.ogg */

	Sound3_dig_gravel4 /* /sound3/dig/gravel4.ogg */

	Sound3_dig_sand1 /* /sound3/dig/sand1.ogg */

	Sound3_dig_sand2 /* /sound3/dig/sand2.ogg */

	Sound3_dig_sand3 /* /sound3/dig/sand3.ogg */

	Sound3_dig_sand4 /* /sound3/dig/sand4.ogg */

	Sound3_dig_snow1 /* /sound3/dig/snow1.ogg */

	Sound3_dig_snow2 /* /sound3/dig/snow2.ogg */

	Sound3_dig_snow3 /* /sound3/dig/snow3.ogg */

	Sound3_dig_snow4 /* /sound3/dig/snow4.ogg */

	Sound3_dig_stone1 /* /sound3/dig/stone1.ogg */

	Sound3_dig_stone2 /* /sound3/dig/stone2.ogg */

	Sound3_dig_stone3 /* /sound3/dig/stone3.ogg */

	Sound3_dig_stone4 /* /sound3/dig/stone4.ogg */

	Sound3_dig_wood1 /* /sound3/dig/wood1.ogg */

	Sound3_dig_wood2 /* /sound3/dig/wood2.ogg */

	Sound3_dig_wood3 /* /sound3/dig/wood3.ogg */

	Sound3_dig_wood4 /* /sound3/dig/wood4.ogg */

	Sound3_fire_fire /* /sound3/fire/fire.ogg */

	Sound3_fire_ignite /* /sound3/fire/ignite.ogg */

	Sound3_fireworks_blast1 /* /sound3/fireworks/blast1.ogg */

	Sound3_fireworks_blast_far1 /* /sound3/fireworks/blast_far1.ogg */

	Sound3_fireworks_largeBlast1 /* /sound3/fireworks/largeBlast1.ogg */

	Sound3_fireworks_largeBlast_far1 /* /sound3/fireworks/largeBlast_far1.ogg */

	Sound3_fireworks_launch1 /* /sound3/fireworks/launch1.ogg */

	Sound3_fireworks_twinkle1 /* /sound3/fireworks/twinkle1.ogg */

	Sound3_fireworks_twinkle_far1 /* /sound3/fireworks/twinkle_far1.ogg */

	Sound3_liquid_lava /* /sound3/liquid/lava.ogg */

	Sound3_liquid_lavapop /* /sound3/liquid/lavapop.ogg */

	Sound3_liquid_splash /* /sound3/liquid/splash.ogg */

	Sound3_liquid_splash2 /* /sound3/liquid/splash2.ogg */

	Sound3_liquid_swim1 /* /sound3/liquid/swim1.ogg */

	Sound3_liquid_swim2 /* /sound3/liquid/swim2.ogg */

	Sound3_liquid_swim3 /* /sound3/liquid/swim3.ogg */

	Sound3_liquid_swim4 /* /sound3/liquid/swim4.ogg */

	Sound3_liquid_water /* /sound3/liquid/water.ogg */

	Sound3_minecart_base /* /sound3/minecart/base.ogg */

	Sound3_minecart_inside /* /sound3/minecart/inside.ogg */

	Sound3_mob_bat_death /* /sound3/mob/bat/death.ogg */

	Sound3_mob_bat_hurt1 /* /sound3/mob/bat/hurt1.ogg */

	Sound3_mob_bat_hurt2 /* /sound3/mob/bat/hurt2.ogg */

	Sound3_mob_bat_hurt3 /* /sound3/mob/bat/hurt3.ogg */

	Sound3_mob_bat_hurt4 /* /sound3/mob/bat/hurt4.ogg */

	Sound3_mob_bat_idle1 /* /sound3/mob/bat/idle1.ogg */

	Sound3_mob_bat_idle2 /* /sound3/mob/bat/idle2.ogg */

	Sound3_mob_bat_idle3 /* /sound3/mob/bat/idle3.ogg */

	Sound3_mob_bat_idle4 /* /sound3/mob/bat/idle4.ogg */

	Sound3_mob_bat_loop /* /sound3/mob/bat/loop.ogg */

	Sound3_mob_bat_takeoff /* /sound3/mob/bat/takeoff.ogg */

	Sound3_mob_blaze_breathe1 /* /sound3/mob/blaze/breathe1.ogg */

	Sound3_mob_blaze_breathe2 /* /sound3/mob/blaze/breathe2.ogg */

	Sound3_mob_blaze_breathe3 /* /sound3/mob/blaze/breathe3.ogg */

	Sound3_mob_blaze_breathe4 /* /sound3/mob/blaze/breathe4.ogg */

	Sound3_mob_blaze_death /* /sound3/mob/blaze/death.ogg */

	Sound3_mob_blaze_hit1 /* /sound3/mob/blaze/hit1.ogg */

	Sound3_mob_blaze_hit2 /* /sound3/mob/blaze/hit2.ogg */

	Sound3_mob_blaze_hit3 /* /sound3/mob/blaze/hit3.ogg */

	Sound3_mob_blaze_hit4 /* /sound3/mob/blaze/hit4.ogg */

	Sound3_mob_cat_hiss1 /* /sound3/mob/cat/hiss1.ogg */

	Sound3_mob_cat_hiss2 /* /sound3/mob/cat/hiss2.ogg */

	Sound3_mob_cat_hiss3 /* /sound3/mob/cat/hiss3.ogg */

	Sound3_mob_cat_hitt1 /* /sound3/mob/cat/hitt1.ogg */

	Sound3_mob_cat_hitt2 /* /sound3/mob/cat/hitt2.ogg */

	Sound3_mob_cat_hitt3 /* /sound3/mob/cat/hitt3.ogg */

	Sound3_mob_cat_meow1 /* /sound3/mob/cat/meow1.ogg */

	Sound3_mob_cat_meow2 /* /sound3/mob/cat/meow2.ogg */

	Sound3_mob_cat_meow3 /* /sound3/mob/cat/meow3.ogg */

	Sound3_mob_cat_meow4 /* /sound3/mob/cat/meow4.ogg */

	Sound3_mob_cat_purr1 /* /sound3/mob/cat/purr1.ogg */

	Sound3_mob_cat_purr2 /* /sound3/mob/cat/purr2.ogg */

	Sound3_mob_cat_purr3 /* /sound3/mob/cat/purr3.ogg */

	Sound3_mob_cat_purreow1 /* /sound3/mob/cat/purreow1.ogg */

	Sound3_mob_cat_purreow2 /* /sound3/mob/cat/purreow2.ogg */

	Sound3_mob_chicken_hurt1 /* /sound3/mob/chicken/hurt1.ogg */

	Sound3_mob_chicken_hurt2 /* /sound3/mob/chicken/hurt2.ogg */

	Sound3_mob_chicken_plop /* /sound3/mob/chicken/plop.ogg */

	Sound3_mob_chicken_say1 /* /sound3/mob/chicken/say1.ogg */

	Sound3_mob_chicken_say2 /* /sound3/mob/chicken/say2.ogg */

	Sound3_mob_chicken_say3 /* /sound3/mob/chicken/say3.ogg */

	Sound3_mob_chicken_step1 /* /sound3/mob/chicken/step1.ogg */

	Sound3_mob_chicken_step2 /* /sound3/mob/chicken/step2.ogg */

	Sound3_mob_cow_hurt1 /* /sound3/mob/cow/hurt1.ogg */

	Sound3_mob_cow_hurt2 /* /sound3/mob/cow/hurt2.ogg */

	Sound3_mob_cow_hurt3 /* /sound3/mob/cow/hurt3.ogg */

	Sound3_mob_cow_say1 /* /sound3/mob/cow/say1.ogg */

	Sound3_mob_cow_say2 /* /sound3/mob/cow/say2.ogg */

	Sound3_mob_cow_say3 /* /sound3/mob/cow/say3.ogg */

	Sound3_mob_cow_say4 /* /sound3/mob/cow/say4.ogg */

	Sound3_mob_cow_step1 /* /sound3/mob/cow/step1.ogg */

	Sound3_mob_cow_step2 /* /sound3/mob/cow/step2.ogg */

	Sound3_mob_cow_step3 /* /sound3/mob/cow/step3.ogg */

	Sound3_mob_cow_step4 /* /sound3/mob/cow/step4.ogg */

	Sound3_mob_creeper_death /* /sound3/mob/creeper/death.ogg */

	Sound3_mob_creeper_say1 /* /sound3/mob/creeper/say1.ogg */

	Sound3_mob_creeper_say2 /* /sound3/mob/creeper/say2.ogg */

	Sound3_mob_creeper_say3 /* /sound3/mob/creeper/say3.ogg */

	Sound3_mob_creeper_say4 /* /sound3/mob/creeper/say4.ogg */

	Sound3_mob_enderdragon_end /* /sound3/mob/enderdragon/end.ogg */

	Sound3_mob_enderdragon_growl1 /* /sound3/mob/enderdragon/growl1.ogg */

	Sound3_mob_enderdragon_growl2 /* /sound3/mob/enderdragon/growl2.ogg */

	Sound3_mob_enderdragon_growl3 /* /sound3/mob/enderdragon/growl3.ogg */

	Sound3_mob_enderdragon_growl4 /* /sound3/mob/enderdragon/growl4.ogg */

	Sound3_mob_enderdragon_hit1 /* /sound3/mob/enderdragon/hit1.ogg */

	Sound3_mob_enderdragon_hit2 /* /sound3/mob/enderdragon/hit2.ogg */

	Sound3_mob_enderdragon_hit3 /* /sound3/mob/enderdragon/hit3.ogg */

	Sound3_mob_enderdragon_hit4 /* /sound3/mob/enderdragon/hit4.ogg */

	Sound3_mob_enderdragon_wings1 /* /sound3/mob/enderdragon/wings1.ogg */

	Sound3_mob_enderdragon_wings2 /* /sound3/mob/enderdragon/wings2.ogg */

	Sound3_mob_enderdragon_wings3 /* /sound3/mob/enderdragon/wings3.ogg */

	Sound3_mob_enderdragon_wings4 /* /sound3/mob/enderdragon/wings4.ogg */

	Sound3_mob_enderdragon_wings5 /* /sound3/mob/enderdragon/wings5.ogg */

	Sound3_mob_enderdragon_wings6 /* /sound3/mob/enderdragon/wings6.ogg */

	Sound3_mob_endermen_death /* /sound3/mob/endermen/death.ogg */

	Sound3_mob_endermen_hit1 /* /sound3/mob/endermen/hit1.ogg */

	Sound3_mob_endermen_hit2 /* /sound3/mob/endermen/hit2.ogg */

	Sound3_mob_endermen_hit3 /* /sound3/mob/endermen/hit3.ogg */

	Sound3_mob_endermen_hit4 /* /sound3/mob/endermen/hit4.ogg */

	Sound3_mob_endermen_idle1 /* /sound3/mob/endermen/idle1.ogg */

	Sound3_mob_endermen_idle2 /* /sound3/mob/endermen/idle2.ogg */

	Sound3_mob_endermen_idle3 /* /sound3/mob/endermen/idle3.ogg */

	Sound3_mob_endermen_idle4 /* /sound3/mob/endermen/idle4.ogg */

	Sound3_mob_endermen_idle5 /* /sound3/mob/endermen/idle5.ogg */

	Sound3_mob_endermen_portal /* /sound3/mob/endermen/portal.ogg */

	Sound3_mob_endermen_portal2 /* /sound3/mob/endermen/portal2.ogg */

	Sound3_mob_endermen_scream1 /* /sound3/mob/endermen/scream1.ogg */

	Sound3_mob_endermen_scream2 /* /sound3/mob/endermen/scream2.ogg */

	Sound3_mob_endermen_scream3 /* /sound3/mob/endermen/scream3.ogg */

	Sound3_mob_endermen_scream4 /* /sound3/mob/endermen/scream4.ogg */

	Sound3_mob_endermen_stare /* /sound3/mob/endermen/stare.ogg */

	Sound3_mob_ghast_affectionate_scream /* /sound3/mob/ghast/affectionate scream.ogg */

	Sound3_mob_ghast_charge /* /sound3/mob/ghast/charge.ogg */

	Sound3_mob_ghast_death /* /sound3/mob/ghast/death.ogg */

	Sound3_mob_ghast_fireball4 /* /sound3/mob/ghast/fireball4.ogg */

	Sound3_mob_ghast_moan1 /* /sound3/mob/ghast/moan1.ogg */

	Sound3_mob_ghast_moan2 /* /sound3/mob/ghast/moan2.ogg */

	Sound3_mob_ghast_moan3 /* /sound3/mob/ghast/moan3.ogg */

	Sound3_mob_ghast_moan4 /* /sound3/mob/ghast/moan4.ogg */

	Sound3_mob_ghast_moan5 /* /sound3/mob/ghast/moan5.ogg */

	Sound3_mob_ghast_moan6 /* /sound3/mob/ghast/moan6.ogg */

	Sound3_mob_ghast_moan7 /* /sound3/mob/ghast/moan7.ogg */

	Sound3_mob_ghast_scream1 /* /sound3/mob/ghast/scream1.ogg */

	Sound3_mob_ghast_scream2 /* /sound3/mob/ghast/scream2.ogg */

	Sound3_mob_ghast_scream3 /* /sound3/mob/ghast/scream3.ogg */

	Sound3_mob_ghast_scream4 /* /sound3/mob/ghast/scream4.ogg */

	Sound3_mob_ghast_scream5 /* /sound3/mob/ghast/scream5.ogg */

	Sound3_mob_irongolem_death /* /sound3/mob/irongolem/death.ogg */

	Sound3_mob_irongolem_hit1 /* /sound3/mob/irongolem/hit1.ogg */

	Sound3_mob_irongolem_hit2 /* /sound3/mob/irongolem/hit2.ogg */

	Sound3_mob_irongolem_hit3 /* /sound3/mob/irongolem/hit3.ogg */

	Sound3_mob_irongolem_hit4 /* /sound3/mob/irongolem/hit4.ogg */

	Sound3_mob_irongolem_throw /* /sound3/mob/irongolem/throw.ogg */

	Sound3_mob_irongolem_walk1 /* /sound3/mob/irongolem/walk1.ogg */

	Sound3_mob_irongolem_walk2 /* /sound3/mob/irongolem/walk2.ogg */

	Sound3_mob_irongolem_walk3 /* /sound3/mob/irongolem/walk3.ogg */

	Sound3_mob_irongolem_walk4 /* /sound3/mob/irongolem/walk4.ogg */

	Sound3_mob_magmacube_big1 /* /sound3/mob/magmacube/big1.ogg */

	Sound3_mob_magmacube_big2 /* /sound3/mob/magmacube/big2.ogg */

	Sound3_mob_magmacube_big3 /* /sound3/mob/magmacube/big3.ogg */

	Sound3_mob_magmacube_big4 /* /sound3/mob/magmacube/big4.ogg */

	Sound3_mob_magmacube_jump1 /* /sound3/mob/magmacube/jump1.ogg */

	Sound3_mob_magmacube_jump2 /* /sound3/mob/magmacube/jump2.ogg */

	Sound3_mob_magmacube_jump3 /* /sound3/mob/magmacube/jump3.ogg */

	Sound3_mob_magmacube_jump4 /* /sound3/mob/magmacube/jump4.ogg */

	Sound3_mob_magmacube_small1 /* /sound3/mob/magmacube/small1.ogg */

	Sound3_mob_magmacube_small2 /* /sound3/mob/magmacube/small2.ogg */

	Sound3_mob_magmacube_small3 /* /sound3/mob/magmacube/small3.ogg */

	Sound3_mob_magmacube_small4 /* /sound3/mob/magmacube/small4.ogg */

	Sound3_mob_magmacube_small5 /* /sound3/mob/magmacube/small5.ogg */

	Sound3_mob_pig_death /* /sound3/mob/pig/death.ogg */

	Sound3_mob_pig_say1 /* /sound3/mob/pig/say1.ogg */

	Sound3_mob_pig_say2 /* /sound3/mob/pig/say2.ogg */

	Sound3_mob_pig_say3 /* /sound3/mob/pig/say3.ogg */

	Sound3_mob_pig_step1 /* /sound3/mob/pig/step1.ogg */

	Sound3_mob_pig_step2 /* /sound3/mob/pig/step2.ogg */

	Sound3_mob_pig_step3 /* /sound3/mob/pig/step3.ogg */

	Sound3_mob_pig_step4 /* /sound3/mob/pig/step4.ogg */

	Sound3_mob_pig_step5 /* /sound3/mob/pig/step5.ogg */

	Sound3_mob_sheep_say1 /* /sound3/mob/sheep/say1.ogg */

	Sound3_mob_sheep_say2 /* /sound3/mob/sheep/say2.ogg */

	Sound3_mob_sheep_say3 /* /sound3/mob/sheep/say3.ogg */

	Sound3_mob_sheep_shear /* /sound3/mob/sheep/shear.ogg */

	Sound3_mob_sheep_step1 /* /sound3/mob/sheep/step1.ogg */

	Sound3_mob_sheep_step2 /* /sound3/mob/sheep/step2.ogg */

	Sound3_mob_sheep_step3 /* /sound3/mob/sheep/step3.ogg */

	Sound3_mob_sheep_step4 /* /sound3/mob/sheep/step4.ogg */

	Sound3_mob_sheep_step5 /* /sound3/mob/sheep/step5.ogg */

	Sound3_mob_silverfish_hit1 /* /sound3/mob/silverfish/hit1.ogg */

	Sound3_mob_silverfish_hit2 /* /sound3/mob/silverfish/hit2.ogg */

	Sound3_mob_silverfish_hit3 /* /sound3/mob/silverfish/hit3.ogg */

	Sound3_mob_silverfish_kill /* /sound3/mob/silverfish/kill.ogg */

	Sound3_mob_silverfish_say1 /* /sound3/mob/silverfish/say1.ogg */

	Sound3_mob_silverfish_say2 /* /sound3/mob/silverfish/say2.ogg */

	Sound3_mob_silverfish_say3 /* /sound3/mob/silverfish/say3.ogg */

	Sound3_mob_silverfish_say4 /* /sound3/mob/silverfish/say4.ogg */

	Sound3_mob_silverfish_step1 /* /sound3/mob/silverfish/step1.ogg */

	Sound3_mob_silverfish_step2 /* /sound3/mob/silverfish/step2.ogg */

	Sound3_mob_silverfish_step3 /* /sound3/mob/silverfish/step3.ogg */

	Sound3_mob_silverfish_step4 /* /sound3/mob/silverfish/step4.ogg */

	Sound3_mob_skeleton_death /* /sound3/mob/skeleton/death.ogg */

	Sound3_mob_skeleton_hurt1 /* /sound3/mob/skeleton/hurt1.ogg */

	Sound3_mob_skeleton_hurt2 /* /sound3/mob/skeleton/hurt2.ogg */

	Sound3_mob_skeleton_hurt3 /* /sound3/mob/skeleton/hurt3.ogg */

	Sound3_mob_skeleton_hurt4 /* /sound3/mob/skeleton/hurt4.ogg */

	Sound3_mob_skeleton_say1 /* /sound3/mob/skeleton/say1.ogg */

	Sound3_mob_skeleton_say2 /* /sound3/mob/skeleton/say2.ogg */

	Sound3_mob_skeleton_say3 /* /sound3/mob/skeleton/say3.ogg */

	Sound3_mob_skeleton_step1 /* /sound3/mob/skeleton/step1.ogg */

	Sound3_mob_skeleton_step2 /* /sound3/mob/skeleton/step2.ogg */

	Sound3_mob_skeleton_step3 /* /sound3/mob/skeleton/step3.ogg */

	Sound3_mob_skeleton_step4 /* /sound3/mob/skeleton/step4.ogg */

	Sound3_mob_slime_attack1 /* /sound3/mob/slime/attack1.ogg */

	Sound3_mob_slime_attack2 /* /sound3/mob/slime/attack2.ogg */

	Sound3_mob_slime_big1 /* /sound3/mob/slime/big1.ogg */

	Sound3_mob_slime_big2 /* /sound3/mob/slime/big2.ogg */

	Sound3_mob_slime_big3 /* /sound3/mob/slime/big3.ogg */

	Sound3_mob_slime_big4 /* /sound3/mob/slime/big4.ogg */

	Sound3_mob_slime_small1 /* /sound3/mob/slime/small1.ogg */

	Sound3_mob_slime_small2 /* /sound3/mob/slime/small2.ogg */

	Sound3_mob_slime_small3 /* /sound3/mob/slime/small3.ogg */

	Sound3_mob_slime_small4 /* /sound3/mob/slime/small4.ogg */

	Sound3_mob_slime_small5 /* /sound3/mob/slime/small5.ogg */

	Sound3_mob_spider_death /* /sound3/mob/spider/death.ogg */

	Sound3_mob_spider_say1 /* /sound3/mob/spider/say1.ogg */

	Sound3_mob_spider_say2 /* /sound3/mob/spider/say2.ogg */

	Sound3_mob_spider_say3 /* /sound3/mob/spider/say3.ogg */

	Sound3_mob_spider_say4 /* /sound3/mob/spider/say4.ogg */

	Sound3_mob_spider_step1 /* /sound3/mob/spider/step1.ogg */

	Sound3_mob_spider_step2 /* /sound3/mob/spider/step2.ogg */

	Sound3_mob_spider_step3 /* /sound3/mob/spider/step3.ogg */

	Sound3_mob_spider_step4 /* /sound3/mob/spider/step4.ogg */

	Sound3_mob_wither_death /* /sound3/mob/wither/death.ogg */

	Sound3_mob_wither_hurt1 /* /sound3/mob/wither/hurt1.ogg */

	Sound3_mob_wither_hurt2 /* /sound3/mob/wither/hurt2.ogg */

	Sound3_mob_wither_hurt3 /* /sound3/mob/wither/hurt3.ogg */

	Sound3_mob_wither_hurt4 /* /sound3/mob/wither/hurt4.ogg */

	Sound3_mob_wither_idle1 /* /sound3/mob/wither/idle1.ogg */

	Sound3_mob_wither_idle2 /* /sound3/mob/wither/idle2.ogg */

	Sound3_mob_wither_idle3 /* /sound3/mob/wither/idle3.ogg */

	Sound3_mob_wither_idle4 /* /sound3/mob/wither/idle4.ogg */

	Sound3_mob_wither_shoot /* /sound3/mob/wither/shoot.ogg */

	Sound3_mob_wither_spawn /* /sound3/mob/wither/spawn.ogg */

	Sound3_mob_wolf_bark1 /* /sound3/mob/wolf/bark1.ogg */

	Sound3_mob_wolf_bark2 /* /sound3/mob/wolf/bark2.ogg */

	Sound3_mob_wolf_bark3 /* /sound3/mob/wolf/bark3.ogg */

	Sound3_mob_wolf_death /* /sound3/mob/wolf/death.ogg */

	Sound3_mob_wolf_growl1 /* /sound3/mob/wolf/growl1.ogg */

	Sound3_mob_wolf_growl2 /* /sound3/mob/wolf/growl2.ogg */

	Sound3_mob_wolf_growl3 /* /sound3/mob/wolf/growl3.ogg */

	Sound3_mob_wolf_howl1 /* /sound3/mob/wolf/howl1.ogg */

	Sound3_mob_wolf_howl2 /* /sound3/mob/wolf/howl2.ogg */

	Sound3_mob_wolf_hurt1 /* /sound3/mob/wolf/hurt1.ogg */

	Sound3_mob_wolf_hurt2 /* /sound3/mob/wolf/hurt2.ogg */

	Sound3_mob_wolf_hurt3 /* /sound3/mob/wolf/hurt3.ogg */

	Sound3_mob_wolf_panting /* /sound3/mob/wolf/panting.ogg */

	Sound3_mob_wolf_shake /* /sound3/mob/wolf/shake.ogg */

	Sound3_mob_wolf_step1 /* /sound3/mob/wolf/step1.ogg */

	Sound3_mob_wolf_step2 /* /sound3/mob/wolf/step2.ogg */

	Sound3_mob_wolf_step3 /* /sound3/mob/wolf/step3.ogg */

	Sound3_mob_wolf_step4 /* /sound3/mob/wolf/step4.ogg */

	Sound3_mob_wolf_step5 /* /sound3/mob/wolf/step5.ogg */

	Sound3_mob_wolf_whine /* /sound3/mob/wolf/whine.ogg */

	Sound3_mob_zombie_death /* /sound3/mob/zombie/death.ogg */

	Sound3_mob_zombie_hurt1 /* /sound3/mob/zombie/hurt1.ogg */

	Sound3_mob_zombie_hurt2 /* /sound3/mob/zombie/hurt2.ogg */

	Sound3_mob_zombie_infect /* /sound3/mob/zombie/infect.ogg */

	Sound3_mob_zombie_metal1 /* /sound3/mob/zombie/metal1.ogg */

	Sound3_mob_zombie_metal2 /* /sound3/mob/zombie/metal2.ogg */

	Sound3_mob_zombie_metal3 /* /sound3/mob/zombie/metal3.ogg */

	Sound3_mob_zombie_remedy /* /sound3/mob/zombie/remedy.ogg */

	Sound3_mob_zombie_say1 /* /sound3/mob/zombie/say1.ogg */

	Sound3_mob_zombie_say2 /* /sound3/mob/zombie/say2.ogg */

	Sound3_mob_zombie_say3 /* /sound3/mob/zombie/say3.ogg */

	Sound3_mob_zombie_step1 /* /sound3/mob/zombie/step1.ogg */

	Sound3_mob_zombie_step2 /* /sound3/mob/zombie/step2.ogg */

	Sound3_mob_zombie_step3 /* /sound3/mob/zombie/step3.ogg */

	Sound3_mob_zombie_step4 /* /sound3/mob/zombie/step4.ogg */

	Sound3_mob_zombie_step5 /* /sound3/mob/zombie/step5.ogg */

	Sound3_mob_zombie_unfect /* /sound3/mob/zombie/unfect.ogg */

	Sound3_mob_zombie_wood1 /* /sound3/mob/zombie/wood1.ogg */

	Sound3_mob_zombie_wood2 /* /sound3/mob/zombie/wood2.ogg */

	Sound3_mob_zombie_wood3 /* /sound3/mob/zombie/wood3.ogg */

	Sound3_mob_zombie_wood4 /* /sound3/mob/zombie/wood4.ogg */

	Sound3_mob_zombie_woodbreak /* /sound3/mob/zombie/woodbreak.ogg */

	Sound3_mob_zombiepig_zpig1 /* /sound3/mob/zombiepig/zpig1.ogg */

	Sound3_mob_zombiepig_zpig2 /* /sound3/mob/zombiepig/zpig2.ogg */

	Sound3_mob_zombiepig_zpig3 /* /sound3/mob/zombiepig/zpig3.ogg */

	Sound3_mob_zombiepig_zpig4 /* /sound3/mob/zombiepig/zpig4.ogg */

	Sound3_mob_zombiepig_zpigangry1 /* /sound3/mob/zombiepig/zpigangry1.ogg */

	Sound3_mob_zombiepig_zpigangry2 /* /sound3/mob/zombiepig/zpigangry2.ogg */

	Sound3_mob_zombiepig_zpigangry3 /* /sound3/mob/zombiepig/zpigangry3.ogg */

	Sound3_mob_zombiepig_zpigangry4 /* /sound3/mob/zombiepig/zpigangry4.ogg */

	Sound3_mob_zombiepig_zpigdeath /* /sound3/mob/zombiepig/zpigdeath.ogg */

	Sound3_mob_zombiepig_zpighurt1 /* /sound3/mob/zombiepig/zpighurt1.ogg */

	Sound3_mob_zombiepig_zpighurt2 /* /sound3/mob/zombiepig/zpighurt2.ogg */

	Sound3_note_bass /* /sound3/note/bass.ogg */

	Sound3_note_bassattack /* /sound3/note/bassattack.ogg */

	Sound3_note_bd /* /sound3/note/bd.ogg */

	Sound3_note_harp /* /sound3/note/harp.ogg */

	Sound3_note_hat /* /sound3/note/hat.ogg */

	Sound3_note_pling /* /sound3/note/pling.ogg */

	Sound3_note_snare /* /sound3/note/snare.ogg */

	Sound3_portal_portal /* /sound3/portal/portal.ogg */

	Sound3_portal_travel /* /sound3/portal/travel.ogg */

	Sound3_portal_trigger /* /sound3/portal/trigger.ogg */

	Sound3_random_anvil_break /* /sound3/random/anvil_break.ogg */

	Sound3_random_anvil_land /* /sound3/random/anvil_land.ogg */

	Sound3_random_anvil_use /* /sound3/random/anvil_use.ogg */

	Sound3_random_bow /* /sound3/random/bow.ogg */

	Sound3_random_bowhit1 /* /sound3/random/bowhit1.ogg */

	Sound3_random_bowhit2 /* /sound3/random/bowhit2.ogg */

	Sound3_random_bowhit3 /* /sound3/random/bowhit3.ogg */

	Sound3_random_bowhit4 /* /sound3/random/bowhit4.ogg */

	Sound3_random_break /* /sound3/random/break.ogg */

	Sound3_random_breath /* /sound3/random/breath.ogg */

	Sound3_random_burp /* /sound3/random/burp.ogg */

	Sound3_random_chestclosed /* /sound3/random/chestclosed.ogg */

	Sound3_random_chestopen /* /sound3/random/chestopen.ogg */

	Sound3_random_classic_hurt /* /sound3/random/classic_hurt.ogg */

	Sound3_random_click /* /sound3/random/click.ogg */

	Sound3_random_door_close /* /sound3/random/door_close.ogg */

	Sound3_random_door_open /* /sound3/random/door_open.ogg */

	Sound3_random_drink /* /sound3/random/drink.ogg */

	Sound3_random_eat1 /* /sound3/random/eat1.ogg */

	Sound3_random_eat2 /* /sound3/random/eat2.ogg */

	Sound3_random_eat3 /* /sound3/random/eat3.ogg */

	Sound3_random_explode1 /* /sound3/random/explode1.ogg */

	Sound3_random_explode2 /* /sound3/random/explode2.ogg */

	Sound3_random_explode3 /* /sound3/random/explode3.ogg */

	Sound3_random_explode4 /* /sound3/random/explode4.ogg */

	Sound3_random_fizz /* /sound3/random/fizz.ogg */

	Sound3_random_fuse /* /sound3/random/fuse.ogg */

	Sound3_random_glass1 /* /sound3/random/glass1.ogg */

	Sound3_random_glass2 /* /sound3/random/glass2.ogg */

	Sound3_random_glass3 /* /sound3/random/glass3.ogg */

	Sound3_random_levelup /* /sound3/random/levelup.ogg */

	Sound3_random_orb /* /sound3/random/orb.ogg */

	Sound3_random_pop /* /sound3/random/pop.ogg */

	Sound3_random_splash /* /sound3/random/splash.ogg */

	Sound3_random_successful_hit /* /sound3/random/successful_hit.ogg */

	Sound3_random_wood_click /* /sound3/random/wood click.ogg */

	Sound3_step_cloth1 /* /sound3/step/cloth1.ogg */

	Sound3_step_cloth2 /* /sound3/step/cloth2.ogg */

	Sound3_step_cloth3 /* /sound3/step/cloth3.ogg */

	Sound3_step_cloth4 /* /sound3/step/cloth4.ogg */

	Sound3_step_grass1 /* /sound3/step/grass1.ogg */

	Sound3_step_grass2 /* /sound3/step/grass2.ogg */

	Sound3_step_grass3 /* /sound3/step/grass3.ogg */

	Sound3_step_grass4 /* /sound3/step/grass4.ogg */

	Sound3_step_grass5 /* /sound3/step/grass5.ogg */

	Sound3_step_grass6 /* /sound3/step/grass6.ogg */

	Sound3_step_gravel1 /* /sound3/step/gravel1.ogg */

	Sound3_step_gravel2 /* /sound3/step/gravel2.ogg */

	Sound3_step_gravel3 /* /sound3/step/gravel3.ogg */

	Sound3_step_gravel4 /* /sound3/step/gravel4.ogg */

	Sound3_step_ladder1 /* /sound3/step/ladder1.ogg */

	Sound3_step_ladder2 /* /sound3/step/ladder2.ogg */

	Sound3_step_ladder3 /* /sound3/step/ladder3.ogg */

	Sound3_step_ladder4 /* /sound3/step/ladder4.ogg */

	Sound3_step_ladder5 /* /sound3/step/ladder5.ogg */

	Sound3_step_sand1 /* /sound3/step/sand1.ogg */

	Sound3_step_sand2 /* /sound3/step/sand2.ogg */

	Sound3_step_sand3 /* /sound3/step/sand3.ogg */

	Sound3_step_sand4 /* /sound3/step/sand4.ogg */

	Sound3_step_sand5 /* /sound3/step/sand5.ogg */

	Sound3_step_snow1 /* /sound3/step/snow1.ogg */

	Sound3_step_snow2 /* /sound3/step/snow2.ogg */

	Sound3_step_snow3 /* /sound3/step/snow3.ogg */

	Sound3_step_snow4 /* /sound3/step/snow4.ogg */

	Sound3_step_stone1 /* /sound3/step/stone1.ogg */

	Sound3_step_stone2 /* /sound3/step/stone2.ogg */

	Sound3_step_stone3 /* /sound3/step/stone3.ogg */

	Sound3_step_stone4 /* /sound3/step/stone4.ogg */

	Sound3_step_stone5 /* /sound3/step/stone5.ogg */

	Sound3_step_stone6 /* /sound3/step/stone6.ogg */

	Sound3_step_wood1 /* /sound3/step/wood1.ogg */

	Sound3_step_wood2 /* /sound3/step/wood2.ogg */

	Sound3_step_wood3 /* /sound3/step/wood3.ogg */

	Sound3_step_wood4 /* /sound3/step/wood4.ogg */

	Sound3_step_wood5 /* /sound3/step/wood5.ogg */

	Sound3_step_wood6 /* /sound3/step/wood6.ogg */

	Sound3_tile_piston_in /* /sound3/tile/piston/in.ogg */

	Sound3_tile_piston_out /* /sound3/tile/piston/out.ogg */

	Streaming_13 /* /streaming/13.ogg */

	Streaming_cat /* /streaming/cat.ogg */

	Terrain_moon /* /terrain/moon.png */

	Terrain_sun /* /terrain/sun.png */

	Terrain /* /terrain.png */

	Title_black /* /title/black.png */

	Title_mclogo /* /title/mclogo.png */

	Title_mojang /* /title/mojang.png */

)

var assetIDtoPath = [...]string{
	"",

	"/armor/chain_1.png",

	"/armor/chain_2.png",

	"/armor/cloth_1.png",

	"/armor/cloth_2.png",

	"/armor/diamond_1.png",

	"/armor/diamond_2.png",

	"/armor/gold_1.png",

	"/armor/gold_2.png",

	"/armor/iron_1.png",

	"/armor/iron_2.png",

	"/armor/power.png",

	"/art/kz.png",

	"/environment/clouds.png",

	"/environment/rain.png",

	"/environment/snow.png",

	"/font/default.png",

	"/gui/background.png",

	"/gui/container.png",

	"/gui/crafting.png",

	"/gui/furnace.png",

	"/gui/gui.png",

	"/gui/icons.png",

	"/gui/inventory.png",

	"/gui/items.png",

	"/gui/logo.png",

	"/gui/particles.png",

	"/gui/slot.png",

	"/gui/trap.png",

	"/gui/unknown_pack.png",

	"/icon.png",

	"/icons/icon_16x16.png",

	"/icons/icon_32x32.png",

	"/item/arrows.png",

	"/item/boat.png",

	"/item/cart.png",

	"/item/door.png",

	"/item/sign.png",

	"/misc/dial.png",

	"/misc/foliagecolor.png",

	"/misc/footprint.png",

	"/misc/grasscolor.png",

	"/misc/mapbg.png",

	"/misc/mapicons.png",

	"/misc/pumpkinblur.png",

	"/misc/shadow.png",

	"/misc/vignette.png",

	"/misc/water.png",

	"/misc/watercolor.png",

	"/mob/char.png",

	"/mob/chicken.png",

	"/mob/cow.png",

	"/mob/creeper.png",

	"/mob/ghast.png",

	"/mob/ghast_fire.png",

	"/mob/pig.png",

	"/mob/pigman.png",

	"/mob/pigzombie.png",

	"/mob/saddle.png",

	"/mob/sheep.png",

	"/mob/sheep_fur.png",

	"/mob/silverfish.png",

	"/mob/skeleton.png",

	"/mob/slime.png",

	"/mob/spider.png",

	"/mob/spider_eyes.png",

	"/mob/squid.png",

	"/mob/wolf.png",

	"/mob/wolf_angry.png",

	"/mob/wolf_tame.png",

	"/mob/zombie.png",

	"/music/calm1.ogg",

	"/music/calm2.ogg",

	"/music/calm3.ogg",

	"/newmusic/hal1.ogg",

	"/newmusic/hal2.ogg",

	"/newmusic/hal3.ogg",

	"/newmusic/hal4.ogg",

	"/newmusic/nuance1.ogg",

	"/newmusic/nuance2.ogg",

	"/newmusic/piano1.ogg",

	"/newmusic/piano2.ogg",

	"/newmusic/piano3.ogg",

	"/newsound/ambient/cave/cave1.ogg",

	"/newsound/ambient/cave/cave10.ogg",

	"/newsound/ambient/cave/cave11.ogg",

	"/newsound/ambient/cave/cave12.ogg",

	"/newsound/ambient/cave/cave13.ogg",

	"/newsound/ambient/cave/cave2.ogg",

	"/newsound/ambient/cave/cave3.ogg",

	"/newsound/ambient/cave/cave4.ogg",

	"/newsound/ambient/cave/cave5.ogg",

	"/newsound/ambient/cave/cave6.ogg",

	"/newsound/ambient/cave/cave7.ogg",

	"/newsound/ambient/cave/cave8.ogg",

	"/newsound/ambient/cave/cave9.ogg",

	"/newsound/ambient/weather/rain1.ogg",

	"/newsound/ambient/weather/rain2.ogg",

	"/newsound/ambient/weather/rain3.ogg",

	"/newsound/ambient/weather/rain4.ogg",

	"/newsound/ambient/weather/thunder1.ogg",

	"/newsound/ambient/weather/thunder2.ogg",

	"/newsound/ambient/weather/thunder3.ogg",

	"/newsound/damage/fallbig1.ogg",

	"/newsound/damage/fallbig2.ogg",

	"/newsound/damage/fallsmall.ogg",

	"/newsound/damage/hurtflesh1.ogg",

	"/newsound/damage/hurtflesh2.ogg",

	"/newsound/damage/hurtflesh3.ogg",

	"/newsound/fire/fire.ogg",

	"/newsound/fire/ignite.ogg",

	"/newsound/liquid/lava.ogg",

	"/newsound/liquid/lavapop.ogg",

	"/newsound/liquid/splash.ogg",

	"/newsound/liquid/water.ogg",

	"/newsound/mob/blaze/breathe1.ogg",

	"/newsound/mob/blaze/breathe2.ogg",

	"/newsound/mob/blaze/breathe3.ogg",

	"/newsound/mob/blaze/breathe4.ogg",

	"/newsound/mob/blaze/death.ogg",

	"/newsound/mob/blaze/hit1.ogg",

	"/newsound/mob/blaze/hit2.ogg",

	"/newsound/mob/blaze/hit3.ogg",

	"/newsound/mob/blaze/hit4.ogg",

	"/newsound/mob/cat/hiss1.ogg",

	"/newsound/mob/cat/hiss2.ogg",

	"/newsound/mob/cat/hiss3.ogg",

	"/newsound/mob/cat/hitt1.ogg",

	"/newsound/mob/cat/hitt2.ogg",

	"/newsound/mob/cat/hitt3.ogg",

	"/newsound/mob/cat/meow1.ogg",

	"/newsound/mob/cat/meow2.ogg",

	"/newsound/mob/cat/meow3.ogg",

	"/newsound/mob/cat/meow4.ogg",

	"/newsound/mob/cat/purr1.ogg",

	"/newsound/mob/cat/purr2.ogg",

	"/newsound/mob/cat/purr3.ogg",

	"/newsound/mob/cat/purreow1.ogg",

	"/newsound/mob/cat/purreow2.ogg",

	"/newsound/mob/chicken1.ogg",

	"/newsound/mob/chicken2.ogg",

	"/newsound/mob/chicken3.ogg",

	"/newsound/mob/chickenhurt1.ogg",

	"/newsound/mob/chickenhurt2.ogg",

	"/newsound/mob/chickenplop.ogg",

	"/newsound/mob/cow1.ogg",

	"/newsound/mob/cow2.ogg",

	"/newsound/mob/cow3.ogg",

	"/newsound/mob/cow4.ogg",

	"/newsound/mob/cowhurt1.ogg",

	"/newsound/mob/cowhurt2.ogg",

	"/newsound/mob/cowhurt3.ogg",

	"/newsound/mob/creeper1.ogg",

	"/newsound/mob/creeper2.ogg",

	"/newsound/mob/creeper3.ogg",

	"/newsound/mob/creeper4.ogg",

	"/newsound/mob/creeperdeath.ogg",

	"/newsound/mob/endermen/death.ogg",

	"/newsound/mob/endermen/hit1.ogg",

	"/newsound/mob/endermen/hit2.ogg",

	"/newsound/mob/endermen/hit3.ogg",

	"/newsound/mob/endermen/hit4.ogg",

	"/newsound/mob/endermen/idle1.ogg",

	"/newsound/mob/endermen/idle2.ogg",

	"/newsound/mob/endermen/idle3.ogg",

	"/newsound/mob/endermen/idle4.ogg",

	"/newsound/mob/endermen/idle5.ogg",

	"/newsound/mob/endermen/portal.ogg",

	"/newsound/mob/endermen/portal2.ogg",

	"/newsound/mob/endermen/scream1.ogg",

	"/newsound/mob/endermen/scream2.ogg",

	"/newsound/mob/endermen/scream3.ogg",

	"/newsound/mob/endermen/scream4.ogg",

	"/newsound/mob/endermen/stare.ogg",

	"/newsound/mob/ghast/affectionate scream.ogg",

	"/newsound/mob/ghast/charge.ogg",

	"/newsound/mob/ghast/death.ogg",

	"/newsound/mob/ghast/fireball4.ogg",

	"/newsound/mob/ghast/moan1.ogg",

	"/newsound/mob/ghast/moan2.ogg",

	"/newsound/mob/ghast/moan3.ogg",

	"/newsound/mob/ghast/moan4.ogg",

	"/newsound/mob/ghast/moan5.ogg",

	"/newsound/mob/ghast/moan6.ogg",

	"/newsound/mob/ghast/moan7.ogg",

	"/newsound/mob/ghast/scream1.ogg",

	"/newsound/mob/ghast/scream2.ogg",

	"/newsound/mob/ghast/scream3.ogg",

	"/newsound/mob/ghast/scream4.ogg",

	"/newsound/mob/ghast/scream5.ogg",

	"/newsound/mob/irongolem/death.ogg",

	"/newsound/mob/irongolem/hit1.ogg",

	"/newsound/mob/irongolem/hit2.ogg",

	"/newsound/mob/irongolem/hit3.ogg",

	"/newsound/mob/irongolem/hit4.ogg",

	"/newsound/mob/irongolem/throw.ogg",

	"/newsound/mob/irongolem/walk1.ogg",

	"/newsound/mob/irongolem/walk2.ogg",

	"/newsound/mob/irongolem/walk3.ogg",

	"/newsound/mob/irongolem/walk4.ogg",

	"/newsound/mob/magmacube/big1.ogg",

	"/newsound/mob/magmacube/big2.ogg",

	"/newsound/mob/magmacube/big3.ogg",

	"/newsound/mob/magmacube/big4.ogg",

	"/newsound/mob/magmacube/jump1.ogg",

	"/newsound/mob/magmacube/jump2.ogg",

	"/newsound/mob/magmacube/jump3.ogg",

	"/newsound/mob/magmacube/jump4.ogg",

	"/newsound/mob/magmacube/small1.ogg",

	"/newsound/mob/magmacube/small2.ogg",

	"/newsound/mob/magmacube/small3.ogg",

	"/newsound/mob/magmacube/small4.ogg",

	"/newsound/mob/magmacube/small5.ogg",

	"/newsound/mob/pig1.ogg",

	"/newsound/mob/pig2.ogg",

	"/newsound/mob/pig3.ogg",

	"/newsound/mob/pigdeath.ogg",

	"/newsound/mob/sheep1.ogg",

	"/newsound/mob/sheep2.ogg",

	"/newsound/mob/sheep3.ogg",

	"/newsound/mob/silverfish/hit1.ogg",

	"/newsound/mob/silverfish/hit2.ogg",

	"/newsound/mob/silverfish/hit3.ogg",

	"/newsound/mob/silverfish/kill.ogg",

	"/newsound/mob/silverfish/say1.ogg",

	"/newsound/mob/silverfish/say2.ogg",

	"/newsound/mob/silverfish/say3.ogg",

	"/newsound/mob/silverfish/say4.ogg",

	"/newsound/mob/silverfish/step1.ogg",

	"/newsound/mob/silverfish/step2.ogg",

	"/newsound/mob/silverfish/step3.ogg",

	"/newsound/mob/silverfish/step4.ogg",

	"/newsound/mob/skeleton1.ogg",

	"/newsound/mob/skeleton2.ogg",

	"/newsound/mob/skeleton3.ogg",

	"/newsound/mob/skeletondeath.ogg",

	"/newsound/mob/skeletonhurt1.ogg",

	"/newsound/mob/skeletonhurt2.ogg",

	"/newsound/mob/skeletonhurt3.ogg",

	"/newsound/mob/skeletonhurt4.ogg",

	"/newsound/mob/slime1.ogg",

	"/newsound/mob/slime2.ogg",

	"/newsound/mob/slime3.ogg",

	"/newsound/mob/slime4.ogg",

	"/newsound/mob/slime5.ogg",

	"/newsound/mob/slimeattack1.ogg",

	"/newsound/mob/slimeattack2.ogg",

	"/newsound/mob/spider1.ogg",

	"/newsound/mob/spider2.ogg",

	"/newsound/mob/spider3.ogg",

	"/newsound/mob/spider4.ogg",

	"/newsound/mob/spiderdeath.ogg",

	"/newsound/mob/wolf/bark1.ogg",

	"/newsound/mob/wolf/bark2.ogg",

	"/newsound/mob/wolf/bark3.ogg",

	"/newsound/mob/wolf/death.ogg",

	"/newsound/mob/wolf/growl1.ogg",

	"/newsound/mob/wolf/growl2.ogg",

	"/newsound/mob/wolf/growl3.ogg",

	"/newsound/mob/wolf/howl1.ogg",

	"/newsound/mob/wolf/howl2.ogg",

	"/newsound/mob/wolf/hurt1.ogg",

	"/newsound/mob/wolf/hurt2.ogg",

	"/newsound/mob/wolf/hurt3.ogg",

	"/newsound/mob/wolf/panting.ogg",

	"/newsound/mob/wolf/shake.ogg",

	"/newsound/mob/wolf/whine.ogg",

	"/newsound/mob/zombie/metal1.ogg",

	"/newsound/mob/zombie/metal2.ogg",

	"/newsound/mob/zombie/metal3.ogg",

	"/newsound/mob/zombie/wood1.ogg",

	"/newsound/mob/zombie/wood2.ogg",

	"/newsound/mob/zombie/wood3.ogg",

	"/newsound/mob/zombie/wood4.ogg",

	"/newsound/mob/zombie/woodbreak.ogg",

	"/newsound/mob/zombie1.ogg",

	"/newsound/mob/zombie2.ogg",

	"/newsound/mob/zombie3.ogg",

	"/newsound/mob/zombiedeath.ogg",

	"/newsound/mob/zombiehurt1.ogg",

	"/newsound/mob/zombiehurt2.ogg",

	"/newsound/mob/zombiepig/zpig1.ogg",

	"/newsound/mob/zombiepig/zpig2.ogg",

	"/newsound/mob/zombiepig/zpig3.ogg",

	"/newsound/mob/zombiepig/zpig4.ogg",

	"/newsound/mob/zombiepig/zpigangry1.ogg",

	"/newsound/mob/zombiepig/zpigangry2.ogg",

	"/newsound/mob/zombiepig/zpigangry3.ogg",

	"/newsound/mob/zombiepig/zpigangry4.ogg",

	"/newsound/mob/zombiepig/zpigdeath.ogg",

	"/newsound/mob/zombiepig/zpighurt1.ogg",

	"/newsound/mob/zombiepig/zpighurt2.ogg",

	"/newsound/note/bass.ogg",

	"/newsound/note/bassattack.ogg",

	"/newsound/note/bd.ogg",

	"/newsound/note/harp.ogg",

	"/newsound/note/hat.ogg",

	"/newsound/note/pling.ogg",

	"/newsound/note/snare.ogg",

	"/newsound/portal/portal.ogg",

	"/newsound/portal/travel.ogg",

	"/newsound/portal/trigger.ogg",

	"/newsound/random/bow.ogg",

	"/newsound/random/bowhit1.ogg",

	"/newsound/random/bowhit2.ogg",

	"/newsound/random/bowhit3.ogg",

	"/newsound/random/bowhit4.ogg",

	"/newsound/random/break.ogg",

	"/newsound/random/breath.ogg",

	"/newsound/random/burp.ogg",

	"/newsound/random/chestclosed.ogg",

	"/newsound/random/chestopen.ogg",

	"/newsound/random/click.ogg",

	"/newsound/random/door_close.ogg",

	"/newsound/random/door_open.ogg",

	"/newsound/random/drink.ogg",

	"/newsound/random/drr.ogg",

	"/newsound/random/eat1.ogg",

	"/newsound/random/eat2.ogg",

	"/newsound/random/eat3.ogg",

	"/newsound/random/explode1.ogg",

	"/newsound/random/explode2.ogg",

	"/newsound/random/explode3.ogg",

	"/newsound/random/explode4.ogg",

	"/newsound/random/fizz.ogg",

	"/newsound/random/fuse.ogg",

	"/newsound/random/glass1.ogg",

	"/newsound/random/glass2.ogg",

	"/newsound/random/glass3.ogg",

	"/newsound/random/hurt.ogg",

	"/newsound/random/levelup.ogg",

	"/newsound/random/old_explode.ogg",

	"/newsound/random/orb.ogg",

	"/newsound/random/pop.ogg",

	"/newsound/random/splash.ogg",

	"/newsound/random/wood click.ogg",

	"/newsound/step/cloth1.ogg",

	"/newsound/step/cloth2.ogg",

	"/newsound/step/cloth3.ogg",

	"/newsound/step/cloth4.ogg",

	"/newsound/step/grass1.ogg",

	"/newsound/step/grass2.ogg",

	"/newsound/step/grass3.ogg",

	"/newsound/step/grass4.ogg",

	"/newsound/step/gravel1.ogg",

	"/newsound/step/gravel2.ogg",

	"/newsound/step/gravel3.ogg",

	"/newsound/step/gravel4.ogg",

	"/newsound/step/sand1.ogg",

	"/newsound/step/sand2.ogg",

	"/newsound/step/sand3.ogg",

	"/newsound/step/sand4.ogg",

	"/newsound/step/snow1.ogg",

	"/newsound/step/snow2.ogg",

	"/newsound/step/snow3.ogg",

	"/newsound/step/snow4.ogg",

	"/newsound/step/stone1.ogg",

	"/newsound/step/stone2.ogg",

	"/newsound/step/stone3.ogg",

	"/newsound/step/stone4.ogg",

	"/newsound/step/wood1.ogg",

	"/newsound/step/wood2.ogg",

	"/newsound/step/wood3.ogg",

	"/newsound/step/wood4.ogg",

	"/newsound/tile/piston/in.ogg",

	"/newsound/tile/piston/out.ogg",

	"/pack.png",

	"/particles.png",

	"/pe/humble.png",

	"/sound/step/grass1.ogg",

	"/sound/step/grass2.ogg",

	"/sound/step/grass3.ogg",

	"/sound/step/grass4.ogg",

	"/sound/step/gravel1.ogg",

	"/sound/step/gravel2.ogg",

	"/sound/step/gravel3.ogg",

	"/sound/step/gravel4.ogg",

	"/sound/step/stone1.ogg",

	"/sound/step/stone2.ogg",

	"/sound/step/stone3.ogg",

	"/sound/step/stone4.ogg",

	"/sound/step/wood1.ogg",

	"/sound/step/wood2.ogg",

	"/sound/step/wood3.ogg",

	"/sound/step/wood4.ogg",

	"/sound3/ambient/cave/cave1.ogg",

	"/sound3/ambient/cave/cave10.ogg",

	"/sound3/ambient/cave/cave11.ogg",

	"/sound3/ambient/cave/cave12.ogg",

	"/sound3/ambient/cave/cave13.ogg",

	"/sound3/ambient/cave/cave2.ogg",

	"/sound3/ambient/cave/cave3.ogg",

	"/sound3/ambient/cave/cave4.ogg",

	"/sound3/ambient/cave/cave5.ogg",

	"/sound3/ambient/cave/cave6.ogg",

	"/sound3/ambient/cave/cave7.ogg",

	"/sound3/ambient/cave/cave8.ogg",

	"/sound3/ambient/cave/cave9.ogg",

	"/sound3/ambient/weather/rain1.ogg",

	"/sound3/ambient/weather/rain2.ogg",

	"/sound3/ambient/weather/rain3.ogg",

	"/sound3/ambient/weather/rain4.ogg",

	"/sound3/ambient/weather/thunder1.ogg",

	"/sound3/ambient/weather/thunder2.ogg",

	"/sound3/ambient/weather/thunder3.ogg",

	"/sound3/damage/fallbig.ogg",

	"/sound3/damage/fallsmall.ogg",

	"/sound3/damage/hit1.ogg",

	"/sound3/damage/hit2.ogg",

	"/sound3/damage/hit3.ogg",

	"/sound3/dig/cloth1.ogg",

	"/sound3/dig/cloth2.ogg",

	"/sound3/dig/cloth3.ogg",

	"/sound3/dig/cloth4.ogg",

	"/sound3/dig/grass1.ogg",

	"/sound3/dig/grass2.ogg",

	"/sound3/dig/grass3.ogg",

	"/sound3/dig/grass4.ogg",

	"/sound3/dig/gravel1.ogg",

	"/sound3/dig/gravel2.ogg",

	"/sound3/dig/gravel3.ogg",

	"/sound3/dig/gravel4.ogg",

	"/sound3/dig/sand1.ogg",

	"/sound3/dig/sand2.ogg",

	"/sound3/dig/sand3.ogg",

	"/sound3/dig/sand4.ogg",

	"/sound3/dig/snow1.ogg",

	"/sound3/dig/snow2.ogg",

	"/sound3/dig/snow3.ogg",

	"/sound3/dig/snow4.ogg",

	"/sound3/dig/stone1.ogg",

	"/sound3/dig/stone2.ogg",

	"/sound3/dig/stone3.ogg",

	"/sound3/dig/stone4.ogg",

	"/sound3/dig/wood1.ogg",

	"/sound3/dig/wood2.ogg",

	"/sound3/dig/wood3.ogg",

	"/sound3/dig/wood4.ogg",

	"/sound3/fire/fire.ogg",

	"/sound3/fire/ignite.ogg",

	"/sound3/fireworks/blast1.ogg",

	"/sound3/fireworks/blast_far1.ogg",

	"/sound3/fireworks/largeBlast1.ogg",

	"/sound3/fireworks/largeBlast_far1.ogg",

	"/sound3/fireworks/launch1.ogg",

	"/sound3/fireworks/twinkle1.ogg",

	"/sound3/fireworks/twinkle_far1.ogg",

	"/sound3/liquid/lava.ogg",

	"/sound3/liquid/lavapop.ogg",

	"/sound3/liquid/splash.ogg",

	"/sound3/liquid/splash2.ogg",

	"/sound3/liquid/swim1.ogg",

	"/sound3/liquid/swim2.ogg",

	"/sound3/liquid/swim3.ogg",

	"/sound3/liquid/swim4.ogg",

	"/sound3/liquid/water.ogg",

	"/sound3/minecart/base.ogg",

	"/sound3/minecart/inside.ogg",

	"/sound3/mob/bat/death.ogg",

	"/sound3/mob/bat/hurt1.ogg",

	"/sound3/mob/bat/hurt2.ogg",

	"/sound3/mob/bat/hurt3.ogg",

	"/sound3/mob/bat/hurt4.ogg",

	"/sound3/mob/bat/idle1.ogg",

	"/sound3/mob/bat/idle2.ogg",

	"/sound3/mob/bat/idle3.ogg",

	"/sound3/mob/bat/idle4.ogg",

	"/sound3/mob/bat/loop.ogg",

	"/sound3/mob/bat/takeoff.ogg",

	"/sound3/mob/blaze/breathe1.ogg",

	"/sound3/mob/blaze/breathe2.ogg",

	"/sound3/mob/blaze/breathe3.ogg",

	"/sound3/mob/blaze/breathe4.ogg",

	"/sound3/mob/blaze/death.ogg",

	"/sound3/mob/blaze/hit1.ogg",

	"/sound3/mob/blaze/hit2.ogg",

	"/sound3/mob/blaze/hit3.ogg",

	"/sound3/mob/blaze/hit4.ogg",

	"/sound3/mob/cat/hiss1.ogg",

	"/sound3/mob/cat/hiss2.ogg",

	"/sound3/mob/cat/hiss3.ogg",

	"/sound3/mob/cat/hitt1.ogg",

	"/sound3/mob/cat/hitt2.ogg",

	"/sound3/mob/cat/hitt3.ogg",

	"/sound3/mob/cat/meow1.ogg",

	"/sound3/mob/cat/meow2.ogg",

	"/sound3/mob/cat/meow3.ogg",

	"/sound3/mob/cat/meow4.ogg",

	"/sound3/mob/cat/purr1.ogg",

	"/sound3/mob/cat/purr2.ogg",

	"/sound3/mob/cat/purr3.ogg",

	"/sound3/mob/cat/purreow1.ogg",

	"/sound3/mob/cat/purreow2.ogg",

	"/sound3/mob/chicken/hurt1.ogg",

	"/sound3/mob/chicken/hurt2.ogg",

	"/sound3/mob/chicken/plop.ogg",

	"/sound3/mob/chicken/say1.ogg",

	"/sound3/mob/chicken/say2.ogg",

	"/sound3/mob/chicken/say3.ogg",

	"/sound3/mob/chicken/step1.ogg",

	"/sound3/mob/chicken/step2.ogg",

	"/sound3/mob/cow/hurt1.ogg",

	"/sound3/mob/cow/hurt2.ogg",

	"/sound3/mob/cow/hurt3.ogg",

	"/sound3/mob/cow/say1.ogg",

	"/sound3/mob/cow/say2.ogg",

	"/sound3/mob/cow/say3.ogg",

	"/sound3/mob/cow/say4.ogg",

	"/sound3/mob/cow/step1.ogg",

	"/sound3/mob/cow/step2.ogg",

	"/sound3/mob/cow/step3.ogg",

	"/sound3/mob/cow/step4.ogg",

	"/sound3/mob/creeper/death.ogg",

	"/sound3/mob/creeper/say1.ogg",

	"/sound3/mob/creeper/say2.ogg",

	"/sound3/mob/creeper/say3.ogg",

	"/sound3/mob/creeper/say4.ogg",

	"/sound3/mob/enderdragon/end.ogg",

	"/sound3/mob/enderdragon/growl1.ogg",

	"/sound3/mob/enderdragon/growl2.ogg",

	"/sound3/mob/enderdragon/growl3.ogg",

	"/sound3/mob/enderdragon/growl4.ogg",

	"/sound3/mob/enderdragon/hit1.ogg",

	"/sound3/mob/enderdragon/hit2.ogg",

	"/sound3/mob/enderdragon/hit3.ogg",

	"/sound3/mob/enderdragon/hit4.ogg",

	"/sound3/mob/enderdragon/wings1.ogg",

	"/sound3/mob/enderdragon/wings2.ogg",

	"/sound3/mob/enderdragon/wings3.ogg",

	"/sound3/mob/enderdragon/wings4.ogg",

	"/sound3/mob/enderdragon/wings5.ogg",

	"/sound3/mob/enderdragon/wings6.ogg",

	"/sound3/mob/endermen/death.ogg",

	"/sound3/mob/endermen/hit1.ogg",

	"/sound3/mob/endermen/hit2.ogg",

	"/sound3/mob/endermen/hit3.ogg",

	"/sound3/mob/endermen/hit4.ogg",

	"/sound3/mob/endermen/idle1.ogg",

	"/sound3/mob/endermen/idle2.ogg",

	"/sound3/mob/endermen/idle3.ogg",

	"/sound3/mob/endermen/idle4.ogg",

	"/sound3/mob/endermen/idle5.ogg",

	"/sound3/mob/endermen/portal.ogg",

	"/sound3/mob/endermen/portal2.ogg",

	"/sound3/mob/endermen/scream1.ogg",

	"/sound3/mob/endermen/scream2.ogg",

	"/sound3/mob/endermen/scream3.ogg",

	"/sound3/mob/endermen/scream4.ogg",

	"/sound3/mob/endermen/stare.ogg",

	"/sound3/mob/ghast/affectionate scream.ogg",

	"/sound3/mob/ghast/charge.ogg",

	"/sound3/mob/ghast/death.ogg",

	"/sound3/mob/ghast/fireball4.ogg",

	"/sound3/mob/ghast/moan1.ogg",

	"/sound3/mob/ghast/moan2.ogg",

	"/sound3/mob/ghast/moan3.ogg",

	"/sound3/mob/ghast/moan4.ogg",

	"/sound3/mob/ghast/moan5.ogg",

	"/sound3/mob/ghast/moan6.ogg",

	"/sound3/mob/ghast/moan7.ogg",

	"/sound3/mob/ghast/scream1.ogg",

	"/sound3/mob/ghast/scream2.ogg",

	"/sound3/mob/ghast/scream3.ogg",

	"/sound3/mob/ghast/scream4.ogg",

	"/sound3/mob/ghast/scream5.ogg",

	"/sound3/mob/irongolem/death.ogg",

	"/sound3/mob/irongolem/hit1.ogg",

	"/sound3/mob/irongolem/hit2.ogg",

	"/sound3/mob/irongolem/hit3.ogg",

	"/sound3/mob/irongolem/hit4.ogg",

	"/sound3/mob/irongolem/throw.ogg",

	"/sound3/mob/irongolem/walk1.ogg",

	"/sound3/mob/irongolem/walk2.ogg",

	"/sound3/mob/irongolem/walk3.ogg",

	"/sound3/mob/irongolem/walk4.ogg",

	"/sound3/mob/magmacube/big1.ogg",

	"/sound3/mob/magmacube/big2.ogg",

	"/sound3/mob/magmacube/big3.ogg",

	"/sound3/mob/magmacube/big4.ogg",

	"/sound3/mob/magmacube/jump1.ogg",

	"/sound3/mob/magmacube/jump2.ogg",

	"/sound3/mob/magmacube/jump3.ogg",

	"/sound3/mob/magmacube/jump4.ogg",

	"/sound3/mob/magmacube/small1.ogg",

	"/sound3/mob/magmacube/small2.ogg",

	"/sound3/mob/magmacube/small3.ogg",

	"/sound3/mob/magmacube/small4.ogg",

	"/sound3/mob/magmacube/small5.ogg",

	"/sound3/mob/pig/death.ogg",

	"/sound3/mob/pig/say1.ogg",

	"/sound3/mob/pig/say2.ogg",

	"/sound3/mob/pig/say3.ogg",

	"/sound3/mob/pig/step1.ogg",

	"/sound3/mob/pig/step2.ogg",

	"/sound3/mob/pig/step3.ogg",

	"/sound3/mob/pig/step4.ogg",

	"/sound3/mob/pig/step5.ogg",

	"/sound3/mob/sheep/say1.ogg",

	"/sound3/mob/sheep/say2.ogg",

	"/sound3/mob/sheep/say3.ogg",

	"/sound3/mob/sheep/shear.ogg",

	"/sound3/mob/sheep/step1.ogg",

	"/sound3/mob/sheep/step2.ogg",

	"/sound3/mob/sheep/step3.ogg",

	"/sound3/mob/sheep/step4.ogg",

	"/sound3/mob/sheep/step5.ogg",

	"/sound3/mob/silverfish/hit1.ogg",

	"/sound3/mob/silverfish/hit2.ogg",

	"/sound3/mob/silverfish/hit3.ogg",

	"/sound3/mob/silverfish/kill.ogg",

	"/sound3/mob/silverfish/say1.ogg",

	"/sound3/mob/silverfish/say2.ogg",

	"/sound3/mob/silverfish/say3.ogg",

	"/sound3/mob/silverfish/say4.ogg",

	"/sound3/mob/silverfish/step1.ogg",

	"/sound3/mob/silverfish/step2.ogg",

	"/sound3/mob/silverfish/step3.ogg",

	"/sound3/mob/silverfish/step4.ogg",

	"/sound3/mob/skeleton/death.ogg",

	"/sound3/mob/skeleton/hurt1.ogg",

	"/sound3/mob/skeleton/hurt2.ogg",

	"/sound3/mob/skeleton/hurt3.ogg",

	"/sound3/mob/skeleton/hurt4.ogg",

	"/sound3/mob/skeleton/say1.ogg",

	"/sound3/mob/skeleton/say2.ogg",

	"/sound3/mob/skeleton/say3.ogg",

	"/sound3/mob/skeleton/step1.ogg",

	"/sound3/mob/skeleton/step2.ogg",

	"/sound3/mob/skeleton/step3.ogg",

	"/sound3/mob/skeleton/step4.ogg",

	"/sound3/mob/slime/attack1.ogg",

	"/sound3/mob/slime/attack2.ogg",

	"/sound3/mob/slime/big1.ogg",

	"/sound3/mob/slime/big2.ogg",

	"/sound3/mob/slime/big3.ogg",

	"/sound3/mob/slime/big4.ogg",

	"/sound3/mob/slime/small1.ogg",

	"/sound3/mob/slime/small2.ogg",

	"/sound3/mob/slime/small3.ogg",

	"/sound3/mob/slime/small4.ogg",

	"/sound3/mob/slime/small5.ogg",

	"/sound3/mob/spider/death.ogg",

	"/sound3/mob/spider/say1.ogg",

	"/sound3/mob/spider/say2.ogg",

	"/sound3/mob/spider/say3.ogg",

	"/sound3/mob/spider/say4.ogg",

	"/sound3/mob/spider/step1.ogg",

	"/sound3/mob/spider/step2.ogg",

	"/sound3/mob/spider/step3.ogg",

	"/sound3/mob/spider/step4.ogg",

	"/sound3/mob/wither/death.ogg",

	"/sound3/mob/wither/hurt1.ogg",

	"/sound3/mob/wither/hurt2.ogg",

	"/sound3/mob/wither/hurt3.ogg",

	"/sound3/mob/wither/hurt4.ogg",

	"/sound3/mob/wither/idle1.ogg",

	"/sound3/mob/wither/idle2.ogg",

	"/sound3/mob/wither/idle3.ogg",

	"/sound3/mob/wither/idle4.ogg",

	"/sound3/mob/wither/shoot.ogg",

	"/sound3/mob/wither/spawn.ogg",

	"/sound3/mob/wolf/bark1.ogg",

	"/sound3/mob/wolf/bark2.ogg",

	"/sound3/mob/wolf/bark3.ogg",

	"/sound3/mob/wolf/death.ogg",

	"/sound3/mob/wolf/growl1.ogg",

	"/sound3/mob/wolf/growl2.ogg",

	"/sound3/mob/wolf/growl3.ogg",

	"/sound3/mob/wolf/howl1.ogg",

	"/sound3/mob/wolf/howl2.ogg",

	"/sound3/mob/wolf/hurt1.ogg",

	"/sound3/mob/wolf/hurt2.ogg",

	"/sound3/mob/wolf/hurt3.ogg",

	"/sound3/mob/wolf/panting.ogg",

	"/sound3/mob/wolf/shake.ogg",

	"/sound3/mob/wolf/step1.ogg",

	"/sound3/mob/wolf/step2.ogg",

	"/sound3/mob/wolf/step3.ogg",

	"/sound3/mob/wolf/step4.ogg",

	"/sound3/mob/wolf/step5.ogg",

	"/sound3/mob/wolf/whine.ogg",

	"/sound3/mob/zombie/death.ogg",

	"/sound3/mob/zombie/hurt1.ogg",

	"/sound3/mob/zombie/hurt2.ogg",

	"/sound3/mob/zombie/infect.ogg",

	"/sound3/mob/zombie/metal1.ogg",

	"/sound3/mob/zombie/metal2.ogg",

	"/sound3/mob/zombie/metal3.ogg",

	"/sound3/mob/zombie/remedy.ogg",

	"/sound3/mob/zombie/say1.ogg",

	"/sound3/mob/zombie/say2.ogg",

	"/sound3/mob/zombie/say3.ogg",

	"/sound3/mob/zombie/step1.ogg",

	"/sound3/mob/zombie/step2.ogg",

	"/sound3/mob/zombie/step3.ogg",

	"/sound3/mob/zombie/step4.ogg",

	"/sound3/mob/zombie/step5.ogg",

	"/sound3/mob/zombie/unfect.ogg",

	"/sound3/mob/zombie/wood1.ogg",

	"/sound3/mob/zombie/wood2.ogg",

	"/sound3/mob/zombie/wood3.ogg",

	"/sound3/mob/zombie/wood4.ogg",

	"/sound3/mob/zombie/woodbreak.ogg",

	"/sound3/mob/zombiepig/zpig1.ogg",

	"/sound3/mob/zombiepig/zpig2.ogg",

	"/sound3/mob/zombiepig/zpig3.ogg",

	"/sound3/mob/zombiepig/zpig4.ogg",

	"/sound3/mob/zombiepig/zpigangry1.ogg",

	"/sound3/mob/zombiepig/zpigangry2.ogg",

	"/sound3/mob/zombiepig/zpigangry3.ogg",

	"/sound3/mob/zombiepig/zpigangry4.ogg",

	"/sound3/mob/zombiepig/zpigdeath.ogg",

	"/sound3/mob/zombiepig/zpighurt1.ogg",

	"/sound3/mob/zombiepig/zpighurt2.ogg",

	"/sound3/note/bass.ogg",

	"/sound3/note/bassattack.ogg",

	"/sound3/note/bd.ogg",

	"/sound3/note/harp.ogg",

	"/sound3/note/hat.ogg",

	"/sound3/note/pling.ogg",

	"/sound3/note/snare.ogg",

	"/sound3/portal/portal.ogg",

	"/sound3/portal/travel.ogg",

	"/sound3/portal/trigger.ogg",

	"/sound3/random/anvil_break.ogg",

	"/sound3/random/anvil_land.ogg",

	"/sound3/random/anvil_use.ogg",

	"/sound3/random/bow.ogg",

	"/sound3/random/bowhit1.ogg",

	"/sound3/random/bowhit2.ogg",

	"/sound3/random/bowhit3.ogg",

	"/sound3/random/bowhit4.ogg",

	"/sound3/random/break.ogg",

	"/sound3/random/breath.ogg",

	"/sound3/random/burp.ogg",

	"/sound3/random/chestclosed.ogg",

	"/sound3/random/chestopen.ogg",

	"/sound3/random/classic_hurt.ogg",

	"/sound3/random/click.ogg",

	"/sound3/random/door_close.ogg",

	"/sound3/random/door_open.ogg",

	"/sound3/random/drink.ogg",

	"/sound3/random/eat1.ogg",

	"/sound3/random/eat2.ogg",

	"/sound3/random/eat3.ogg",

	"/sound3/random/explode1.ogg",

	"/sound3/random/explode2.ogg",

	"/sound3/random/explode3.ogg",

	"/sound3/random/explode4.ogg",

	"/sound3/random/fizz.ogg",

	"/sound3/random/fuse.ogg",

	"/sound3/random/glass1.ogg",

	"/sound3/random/glass2.ogg",

	"/sound3/random/glass3.ogg",

	"/sound3/random/levelup.ogg",

	"/sound3/random/orb.ogg",

	"/sound3/random/pop.ogg",

	"/sound3/random/splash.ogg",

	"/sound3/random/successful_hit.ogg",

	"/sound3/random/wood click.ogg",

	"/sound3/step/cloth1.ogg",

	"/sound3/step/cloth2.ogg",

	"/sound3/step/cloth3.ogg",

	"/sound3/step/cloth4.ogg",

	"/sound3/step/grass1.ogg",

	"/sound3/step/grass2.ogg",

	"/sound3/step/grass3.ogg",

	"/sound3/step/grass4.ogg",

	"/sound3/step/grass5.ogg",

	"/sound3/step/grass6.ogg",

	"/sound3/step/gravel1.ogg",

	"/sound3/step/gravel2.ogg",

	"/sound3/step/gravel3.ogg",

	"/sound3/step/gravel4.ogg",

	"/sound3/step/ladder1.ogg",

	"/sound3/step/ladder2.ogg",

	"/sound3/step/ladder3.ogg",

	"/sound3/step/ladder4.ogg",

	"/sound3/step/ladder5.ogg",

	"/sound3/step/sand1.ogg",

	"/sound3/step/sand2.ogg",

	"/sound3/step/sand3.ogg",

	"/sound3/step/sand4.ogg",

	"/sound3/step/sand5.ogg",

	"/sound3/step/snow1.ogg",

	"/sound3/step/snow2.ogg",

	"/sound3/step/snow3.ogg",

	"/sound3/step/snow4.ogg",

	"/sound3/step/stone1.ogg",

	"/sound3/step/stone2.ogg",

	"/sound3/step/stone3.ogg",

	"/sound3/step/stone4.ogg",

	"/sound3/step/stone5.ogg",

	"/sound3/step/stone6.ogg",

	"/sound3/step/wood1.ogg",

	"/sound3/step/wood2.ogg",

	"/sound3/step/wood3.ogg",

	"/sound3/step/wood4.ogg",

	"/sound3/step/wood5.ogg",

	"/sound3/step/wood6.ogg",

	"/sound3/tile/piston/in.ogg",

	"/sound3/tile/piston/out.ogg",

	"/streaming/13.ogg",

	"/streaming/cat.ogg",

	"/terrain/moon.png",

	"/terrain/sun.png",

	"/terrain.png",

	"/title/black.png",

	"/title/mclogo.png",

	"/title/mojang.png",
}

// Get string path for asset id
func (a ID) String() string {
	return assetIDtoPath[a]
}
